// 用語集。readingで五十音ソートされる。
export default [
  { term: 'アタッチメント（愛着）', reading: 'あたっちめんと', slug: 'attachment',
    definition: '子と養育者の間に築かれる情緒的な絆。安全基地となり、探索・学習・自己制御の土台になる。',
    see_also: ['安全基地', 'サーブ＆リターン'] },
  { term: '安全基地', reading: 'あんぜんきち', slug: 'secure-base',
    definition: '子が安心して世界を探索し、不安になれば戻れる拠り所となる養育者の役割。愛着が安定すると機能する。',
    see_also: ['アタッチメント'] },
  { term: 'ヴィデオ・デフィシット', reading: 'ういでおでふぃしっと', slug: 'video-deficit',
    definition: '2歳未満の乳児が、同じ内容を対面より動画からは学びにくい現象。乳児向け知育動画の効果が乏しい理由。',
    see_also: ['スクリーンタイム'] },
  { term: 'エビデンスレベル', reading: 'えびでんすれべる', slug: 'evidence-level',
    definition: '主張の確からしさの等級（本資料ではA〜D）。Aが最も強く、Dは人気だが根拠が薄い。',
    see_also: [] },
  { term: '基礎的動作スキル（FMS）', reading: 'きそてきどうさすきる', slug: 'fms',
    definition: '走る・跳ぶ・投げる・捕る・蹴る・バランスなど、あらゆるスポーツの土台となる基本動作。幼児期に幅広く育てる。',
    see_also: ['身体リテラシー', 'ABC'] },
  { term: '共同注意', reading: 'きょうどうちゅうい', slug: 'joint-attention',
    definition: '子と大人が同じ対象に注意を向け合うこと。指さしや視線追いで成立し、語彙獲得の重要な土台。',
    see_also: ['サーブ＆リターン', '言語のシャワー'] },
  { term: '臨界期', reading: 'りんかいき', slug: 'critical-period',
    definition: 'その時期を過ぎると学習が極めて困難になる発達の窓。視覚や第一言語の音韻など一部に限られる。',
    see_also: ['敏感期'] },
  { term: '敏感期', reading: 'びんかんき', slug: 'sensitive-period',
    definition: '特定の学習が起こりやすい時期。ただし過ぎても学習は可能で、窓は閉じない。多くの能力はこちら。',
    see_also: ['臨界期'] },
  { term: 'サーブ＆リターン', reading: 'さーぶあんどりたーん', slug: 'serve-return',
    definition: '子の発信に養育者が即座に意味を持って応じる往復のやりとり。神経回路形成の基本単位で、最も根拠の強い関わり。',
    see_also: ['アタッチメント', '共同注意'] },
  { term: '実行機能（EF）', reading: 'じっこうきのう', slug: 'executive-function',
    definition: 'ワーキングメモリ・抑制制御・認知的柔軟性からなる"脳の司令塔"。学業成功の強力な予測因子。',
    see_also: ['ワーキングメモリ', '足場かけ'] },
  { term: '身体リテラシー', reading: 'しんたいりてらしー', slug: 'physical-literacy',
    definition: '多様な動作を自信を持って楽しめる能力と意欲。特定競技より優先して幼児期に育てるべきもの。',
    see_also: ['基礎的動作スキル（FMS）'] },
  { term: 'シナプスの刈り込み', reading: 'しなぷすのかりこみ', slug: 'pruning',
    definition: '過剰に作られた神経結合のうち、使われないものを整理する過程。経験がどの回路を残すかを決める。',
    see_also: ['可塑性'] },
  { term: '足場かけ（スキャフォールディング）', reading: 'あしばかけ', slug: 'scaffolding',
    definition: '子が一人では難しいが手助けがあればできる課題を、少し支えながら挑戦させる関わり。発達の最近接領域を活かす。',
    see_also: ['実行機能（EF）'] },
  { term: '毒性ストレス', reading: 'どくせいすとれす', slug: 'toxic-stress',
    definition: '強く長期にわたり、支えとなる大人がいない中で受けるストレス。脳の発達を妨げる。応答的な関係が緩衝材になる。',
    see_also: ['アタッチメント'] },
  { term: '対話的読み聞かせ', reading: 'たいわてきよみきかせ', slug: 'dialogic-reading',
    definition: '読み上げるだけでなく問いかけ、子の答えを広げる読み聞かせ法。語彙と読解の前駆スキルに効果的。',
    see_also: ['言語のシャワー'] },
  { term: '言語のシャワー', reading: 'げんごのしゃわー', slug: 'language-bath',
    definition: '子が日常で浴びる言葉の量と質。後の語彙・読解・学業と関連する。応答的な語りかけが鍵。',
    see_also: ['サーブ＆リターン', '共同注意'] },
  { term: 'ワーキングメモリ', reading: 'わーきんぐめもり', slug: 'working-memory',
    definition: '情報を一時的に保持しながら操作する能力。実行機能の中核で、暗算や指示の記憶に使う。',
    see_also: ['実行機能（EF）'] },
  { term: 'ABC（運動）', reading: 'えーびーしー', slug: 'abc-motor',
    definition: 'Agility（敏捷性）・Balance（バランス）・Coordination（協応）。幼児期の運動で育てたい3要素。',
    see_also: ['基礎的動作スキル（FMS）'] },
  { term: '可塑性（脳の）', reading: 'かそせい', slug: 'plasticity',
    definition: '経験に応じて脳が自らの配線を変える力。乳幼児期に最も高く、学びの土台。回復力の源でもある。',
    see_also: ['シナプスの刈り込み', '髄鞘化（ミエリン化）'] },
  { term: '髄鞘化（ミエリン化）', reading: 'ずいしょうか', slug: 'myelination',
    definition: '神経の軸索に絶縁体ミエリンが巻かれ信号伝達が高速化する過程。幼児期から10代以降までゆっくり続く。',
    see_also: ['可塑性（脳の）'] },
  { term: '前庭感覚', reading: 'ぜんていかんかく', slug: 'vestibular',
    definition: '傾き・回転・加速を捉える感覚。姿勢制御・バランス・空間で自分を捉える力の土台。揺れ・高低の遊びで育つ。',
    see_also: ['固有感覚', '感覚統合'] },
  { term: '固有感覚', reading: 'こゆうかんかく', slug: 'proprioception',
    definition: '体の位置や力加減を捉える感覚。押す・引く・持ち上げる経験で体の"地図"が精緻になる。',
    see_also: ['前庭感覚'] },
  { term: '感覚統合', reading: 'かんかくとうごう', slug: 'sensory-integration',
    definition: '視覚・聴覚・触覚・運動などの感覚を脳でまとめ意味づける働き。多感覚の一致した経験で育つ。',
    see_also: ['前庭感覚', '固有感覚'] },
  { term: '社会的参照', reading: 'しゃかいてきさんしょう', slug: 'social-referencing',
    definition: '新しい物事に出会ったとき養育者の表情を確認し行動を決めること。9〜12ヶ月ごろ明確になる。',
    see_also: ['アタッチメント（愛着）', '安全基地'] },
  { term: 'ラフ＆タンブル遊び', reading: 'らふあんどたんぶる', slug: 'rough-and-tumble',
    definition: '取っ組み合いなど活発な身体遊び。父親に多く、興奮の調整・体の制御・社会性を育てる。',
    see_also: ['前庭感覚', '情動調整'] },
  { term: '情動調整', reading: 'じょうどうちょうせい', slug: 'emotion-regulation',
    definition: '感情を認識し落ち着ける力。学業・人間関係の土台で、実行機能と深く重なる。名づけと受容で育つ。',
    see_also: ['実行機能（EF）', '毒性ストレス'] },
  { term: '賦活の関係', reading: 'ふかつのかんけい', slug: 'activation-relationship',
    definition: '子を探索・挑戦へ押し出す関わり。父親に多く観察され、安全基地（戻る安心）と相補的に働く。',
    see_also: ['安全基地', 'アタッチメント（愛着）'] },
  { term: '知覚の絞り込み', reading: 'ちかくのしぼりこみ', slug: 'perceptual-narrowing',
    definition: '母語で使う音の対比だけを残し、使わない対比の弁別が弱まる乳児期の現象。生後6〜12ヶ月ごろ。',
    see_also: ['臨界期', '敏感期'] },
  { term: '早期特化', reading: 'そうきとっか', slug: 'early-specialization',
    definition: '幼少から一競技に絞る訓練。多くの競技で障害・燃え尽きと関連し不利になりうる。幼児期は多様化が原則。',
    see_also: ['身体リテラシー', '基礎的動作スキル（FMS）'] },
  { term: '身体的有能感', reading: 'しんたいてきゆうのうかん', slug: 'physical-competence',
    definition: '「自分は体を動かすのが得意」という自己認識。運動継続と技能向上の好循環を生む。成功体験で育つ。',
    see_also: ['身体リテラシー', '早期特化'] },
  { term: '脱文脈の会話', reading: 'だつぶんみゃくのかいわ', slug: 'decontextualized-talk',
    definition: '今ここにない出来事（過去・未来・想像）を言葉で語る会話。物語る力を育て後の読解・作文と関連。',
    see_also: ['言語のシャワー', '対話的読み聞かせ'] },
];
