// 用語集。readingで五十音ソートされる。
export default [
  { term: 'アタッチメント（愛着）', reading: 'あたっちめんと', slug: 'attachment',
    definition: '子と養育者の間に築かれる情緒的な絆。安全基地となり、探索・学習・自己制御の土台になる。',
    see_also: ['安全基地', 'サーブ＆リターン'] },
  { term: '安全基地', reading: 'あんぜんきち', slug: 'secure-base',
    definition: '子が安心して世界を探索し、不安になれば戻れる拠り所となる養育者の役割。愛着が安定すると機能する。',
    see_also: ['アタッチメント'] },
  { term: 'ヴィデオ・デフィシット', reading: 'ういでおでふぃしっと', slug: 'video-deficit',
    definition: '2歳未満の乳児が、同じ内容を対面より動画からは学びにくい現象。乳児向け知育動画の効果が乏しい理由。',
    see_also: ['スクリーンタイム'] },
  { term: 'エビデンスレベル', reading: 'えびでんすれべる', slug: 'evidence-level',
    definition: '主張の確からしさの等級（本資料ではA〜D）。Aが最も強く、Dは人気だが根拠が薄い。',
    see_also: [] },
  { term: '基礎的動作スキル（FMS）', reading: 'きそてきどうさすきる', slug: 'fms',
    definition: '走る・跳ぶ・投げる・捕る・蹴る・バランスなど、あらゆるスポーツの土台となる基本動作。幼児期に幅広く育てる。',
    see_also: ['身体リテラシー', 'ABC'] },
  { term: '共同注意', reading: 'きょうどうちゅうい', slug: 'joint-attention',
    definition: '子と大人が同じ対象に注意を向け合うこと。指さしや視線追いで成立し、語彙獲得の重要な土台。',
    see_also: ['サーブ＆リターン', '言語のシャワー'] },
  { term: '臨界期', reading: 'りんかいき', slug: 'critical-period',
    definition: 'その時期を過ぎると学習が極めて困難になる発達の窓。視覚や第一言語の音韻など一部に限られる。',
    see_also: ['敏感期'] },
  { term: '敏感期', reading: 'びんかんき', slug: 'sensitive-period',
    definition: '特定の学習が起こりやすい時期。ただし過ぎても学習は可能で、窓は閉じない。多くの能力はこちら。',
    see_also: ['臨界期'] },
  { term: 'サーブ＆リターン', reading: 'さーぶあんどりたーん', slug: 'serve-return',
    definition: '子の発信に養育者が即座に意味を持って応じる往復のやりとり。神経回路形成の基本単位で、最も根拠の強い関わり。',
    see_also: ['アタッチメント', '共同注意'] },
  { term: '実行機能（EF）', reading: 'じっこうきのう', slug: 'executive-function',
    definition: 'ワーキングメモリ・抑制制御・認知的柔軟性からなる"脳の司令塔"。学業成功の強力な予測因子。',
    see_also: ['ワーキングメモリ', '足場かけ'] },
  { term: '身体リテラシー', reading: 'しんたいりてらしー', slug: 'physical-literacy',
    definition: '多様な動作を自信を持って楽しめる能力と意欲。特定競技より優先して幼児期に育てるべきもの。',
    see_also: ['基礎的動作スキル（FMS）'] },
  { term: 'シナプスの刈り込み', reading: 'しなぷすのかりこみ', slug: 'pruning',
    definition: '過剰に作られた神経結合のうち、使われないものを整理する過程。経験がどの回路を残すかを決める。',
    see_also: ['可塑性'] },
  { term: '足場かけ（スキャフォールディング）', reading: 'あしばかけ', slug: 'scaffolding',
    definition: '子が一人では難しいが手助けがあればできる課題を、少し支えながら挑戦させる関わり。発達の最近接領域を活かす。',
    see_also: ['実行機能（EF）'] },
  { term: '毒性ストレス', reading: 'どくせいすとれす', slug: 'toxic-stress',
    definition: '強く長期にわたり、支えとなる大人がいない中で受けるストレス。脳の発達を妨げる。応答的な関係が緩衝材になる。',
    see_also: ['アタッチメント'] },
  { term: '対話的読み聞かせ', reading: 'たいわてきよみきかせ', slug: 'dialogic-reading',
    definition: '読み上げるだけでなく問いかけ、子の答えを広げる読み聞かせ法。語彙と読解の前駆スキルに効果的。',
    see_also: ['言語のシャワー'] },
  { term: '言語のシャワー', reading: 'げんごのしゃわー', slug: 'language-bath',
    definition: '子が日常で浴びる言葉の量と質。後の語彙・読解・学業と関連する。応答的な語りかけが鍵。',
    see_also: ['サーブ＆リターン', '共同注意'] },
  { term: 'ワーキングメモリ', reading: 'わーきんぐめもり', slug: 'working-memory',
    definition: '情報を一時的に保持しながら操作する能力。実行機能の中核で、暗算や指示の記憶に使う。',
    see_also: ['実行機能（EF）'] },
  { term: 'ABC（運動）', reading: 'えーびーしー', slug: 'abc-motor',
    definition: 'Agility（敏捷性）・Balance（バランス）・Coordination（協応）。幼児期の運動で育てたい3要素。',
    see_also: ['基礎的動作スキル（FMS）'] },
  { term: '可塑性（脳の）', reading: 'かそせい', slug: 'plasticity',
    definition: '経験に応じて脳が自らの配線を変える力。乳幼児期に最も高く、学びの土台。回復力の源でもある。',
    see_also: ['シナプスの刈り込み', '髄鞘化（ミエリン化）'] },
  { term: '髄鞘化（ミエリン化）', reading: 'ずいしょうか', slug: 'myelination',
    definition: '神経の軸索に絶縁体ミエリンが巻かれ信号伝達が高速化する過程。幼児期から10代以降までゆっくり続く。',
    see_also: ['可塑性（脳の）'] },
  { term: '前庭感覚', reading: 'ぜんていかんかく', slug: 'vestibular',
    definition: '傾き・回転・加速を捉える感覚。姿勢制御・バランス・空間で自分を捉える力の土台。揺れ・高低の遊びで育つ。',
    see_also: ['固有感覚', '感覚統合'] },
  { term: '固有感覚', reading: 'こゆうかんかく', slug: 'proprioception',
    definition: '体の位置や力加減を捉える感覚。押す・引く・持ち上げる経験で体の"地図"が精緻になる。',
    see_also: ['前庭感覚'] },
  { term: '感覚統合', reading: 'かんかくとうごう', slug: 'sensory-integration',
    definition: '視覚・聴覚・触覚・運動などの感覚を脳でまとめ意味づける働き。多感覚の一致した経験で育つ。',
    see_also: ['前庭感覚', '固有感覚'] },
  { term: '社会的参照', reading: 'しゃかいてきさんしょう', slug: 'social-referencing',
    definition: '新しい物事に出会ったとき養育者の表情を確認し行動を決めること。9〜12ヶ月ごろ明確になる。',
    see_also: ['アタッチメント（愛着）', '安全基地'] },
  { term: 'ラフ＆タンブル遊び', reading: 'らふあんどたんぶる', slug: 'rough-and-tumble',
    definition: '取っ組み合いなど活発な身体遊び。父親に多く、興奮の調整・体の制御・社会性を育てる。',
    see_also: ['前庭感覚', '情動調整'] },
  { term: '情動調整', reading: 'じょうどうちょうせい', slug: 'emotion-regulation',
    definition: '感情を認識し落ち着ける力。学業・人間関係の土台で、実行機能と深く重なる。名づけと受容で育つ。',
    see_also: ['実行機能（EF）', '毒性ストレス'] },
  { term: '賦活の関係', reading: 'ふかつのかんけい', slug: 'activation-relationship',
    definition: '子を探索・挑戦へ押し出す関わり。父親に多く観察され、安全基地（戻る安心）と相補的に働く。',
    see_also: ['安全基地', 'アタッチメント（愛着）'] },
  { term: '知覚の絞り込み', reading: 'ちかくのしぼりこみ', slug: 'perceptual-narrowing',
    definition: '母語で使う音の対比だけを残し、使わない対比の弁別が弱まる乳児期の現象。生後6〜12ヶ月ごろ。',
    see_also: ['臨界期', '敏感期'] },
  { term: '早期特化', reading: 'そうきとっか', slug: 'early-specialization',
    definition: '幼少から一競技に絞る訓練。多くの競技で障害・燃え尽きと関連し不利になりうる。幼児期は多様化が原則。',
    see_also: ['身体リテラシー', '基礎的動作スキル（FMS）'] },
  { term: '身体的有能感', reading: 'しんたいてきゆうのうかん', slug: 'physical-competence',
    definition: '「自分は体を動かすのが得意」という自己認識。運動継続と技能向上の好循環を生む。成功体験で育つ。',
    see_also: ['身体リテラシー', '早期特化'] },
  { term: '脱文脈の会話', reading: 'だつぶんみゃくのかいわ', slug: 'decontextualized-talk',
    definition: '今ここにない出来事（過去・未来・想像）を言葉で語る会話。物語る力を育て後の読解・作文と関連。',
    see_also: ['言語のシャワー', '対話的読み聞かせ'] },
  { term: '気質', reading: 'きしつ', slug: 'temperament',
    definition: '刺激への反応や感情の出方の、生まれつきの傾向（活発さ・敏感さ・順応性など）。良し悪しはなく、環境との相性で表れ方が変わる。',
    see_also: ['相性（適合の良さ）', '差次感受性'] },
  { term: '相性（適合の良さ）', reading: 'あいしょう', slug: 'goodness-of-fit',
    definition: '子の気質と、環境・親の関わり・求められることが噛み合っている度合い。「育てにくさ」は気質そのものより、この相性の問題。',
    see_also: ['気質', '足場かけ（スキャフォールディング）'] },
  { term: '差次感受性', reading: 'さじかんじゅせい', slug: 'differential-susceptibility',
    definition: '敏感な子ほど、悪い環境では傷つきやすい一方、良い環境ではむしろ人一倍伸びやすいという考え方（「タンポポとラン」）。検証途上（等級C）。',
    see_also: ['気質', '相性（適合の良さ）'] },
  { term: '音韻意識', reading: 'おんいんいしき', slug: 'phonological-awareness',
    definition: '言葉が音のかたまりでできていると気づく力（拍・韻・頭の音）。文字を音に変換する読みの前提で、しりとり・韻遊びで育つ。',
    see_also: ['対話的読み聞かせ', '言語のシャワー'] },
  { term: '数量感覚', reading: 'すうりょうかんかく', slug: 'number-sense',
    definition: '数と量を意味として直感的につかむ力（多い/少ない、いくつ）。生まれつきの近似数感覚を、言葉と経験で磨く。数唱（暗唱）とは別物。',
    see_also: ['サビタイジング', '基数性'] },
  { term: 'サビタイジング', reading: 'さびたいじんぐ', slug: 'subitizing',
    definition: '2〜3個程度なら、数えずにパッと個数が分かる力。数と量が結びつき始めたサイン。',
    see_also: ['数量感覚', '基数性'] },
  { term: '基数性', reading: 'きすうせい', slug: 'cardinality',
    definition: '数えたときの「最後に言った数＝全体の個数」だと分かること。数唱が意味を持つための鍵。',
    see_also: ['数量感覚', 'サビタイジング'] },
  { term: '相対年齢効果', reading: 'そうたいねんれいこうか', slug: 'relative-age-effect',
    definition: '同学年内の月齢差で、早生まれがやや不利に見える現象。成熟の差であって能力差ではなく、学年とともに縮小する。',
    see_also: [] },
  { term: 'ピンサーグリップ', reading: 'ぴんさーぐりっぷ', slug: 'pincer-grip',
    definition: '親指と人差し指の先で小さな物をつまむ精密な握り。おおむね生後9〜12ヶ月で獲得し、自分で食べる・道具使用の入り口。',
    see_also: ['基礎的動作スキル（FMS）'] },
  { term: 'ルーズパーツ', reading: 'るーずぱーつ', slug: 'loose-parts',
    definition: '使い方が決まっておらず、動かし組み合わせられる素材（箱・布・石・容器など）。発明と発見の機会を増やすオープンエンドな遊びの核。',
    see_also: ['足場かけ（スキャフォールディング）'] },
  { term: '対乳児発話（parentese）', reading: 'たいにゅうじはつわ', slug: 'parentese',
    definition: '赤ちゃんに向かうと自然に出る、高め・大きな抑揚・ゆっくり・はっきりの話し方。文法は正しいまま。注意と音の学習を助ける。',
    see_also: ['言語のシャワー', 'サーブ＆リターン'] },
  { term: 'ふり遊び（象徴遊び）', reading: 'ふりあそび', slug: 'pretend-play',
    definition: '目の前にない物・場面を思い描いて演じる遊び。言語・自己制御・他者理解・抽象化を同時に育てる。見立て→役割ごっこと発達する。',
    see_also: ['実行機能（EF）', '足場かけ（スキャフォールディング）'] },
  { term: 'アンダーマイニング効果', reading: 'あんだーまいにんぐこうか', slug: 'undermining-effect',
    definition: 'もともと好きな活動に物的報酬（シール・お菓子）を持ち込むと、かえって内発的な興味が下がる現象。遊びやお手伝いに報酬を混ぜない根拠。',
    see_also: [] },
  { term: 'リスクのある遊び', reading: 'りすくのあるあそび', slug: 'risky-play',
    definition: '登る・高い所から跳ぶ・スピードを出すなど、適度な危なさを含む遊び。体の使い方・危険の見積もり・自信を育てる。過保護と無謀の間を設計する。',
    see_also: ['前庭感覚', 'ラフ＆タンブル遊び'] },
  { term: '空間認知', reading: 'くうかんにんち', slug: 'spatial-cognition',
    definition: '形・位置・向き・大きさを頭の中でイメージして操作する力。積む・回す・空間のことばで育ち、後の数学・STEMと関連する。',
    see_also: ['数量感覚'] },
  { term: 'スクリーンタイム', reading: 'すくりーんたいむ', slug: 'screen-time',
    definition: '画面を見て過ごす時間。0〜2歳では多感覚性と応答性を欠くため学びに乏しく、やりとり・外遊び・睡眠を削らないかで見る。',
    see_also: ['ヴィデオ・デフィシット'] },
  { term: '並行遊び', reading: 'へいこうあそび', slug: 'parallel-play',
    definition: '隣で同じような遊びを別々にする段階。2〜3歳の主役で、協同遊びの前段階。見て・まねる社会学習が進む時間であり、社会性の不足ではない。',
    see_also: ['ふり遊び（象徴遊び）'] },
  { term: '対象の永続性', reading: 'たいしょうのえいぞくせい', slug: 'object-permanence',
    definition: '見えなくなった物や人が、存在し続けていると分かる力。生後半年ごろから育ち、いないいないばあが楽しくなる理由であり、分離不安の前提でもある。',
    see_also: ['分離不安（8ヶ月不安）'] },
  { term: '分離不安（8ヶ月不安）', reading: 'ぶんりふあん', slug: 'separation-anxiety',
    definition: '特定の相手と離れることへの強い不安。8ヶ月前後から現れ、愛着が形成された証拠。「戻ってくる」の見通しが育つにつれ落ち着く。',
    see_also: ['アタッチメント（愛着）', '対象の永続性', '移行対象'] },
  { term: '移行対象', reading: 'いこうたいしょう', slug: 'transitional-object',
    definition: 'お気に入りの布・ぬいぐるみなど、親の代わりに安心を持ち運べる物。分離の場面や入眠時に自分を落ち着かせる道具になる。',
    see_also: ['分離不安（8ヶ月不安）'] },
  { term: '退行（赤ちゃん返り）', reading: 'たいこう', slug: 'regression',
    definition: '大きな環境変化のあと、できていた行動が一時的に前の段階へ戻る現象。不安への正常な適応で、叱責より安心の供給を増やすと早く戻る。',
    see_also: ['分離不安（8ヶ月不安）', '毒性ストレス'] },
  { term: '語彙爆発', reading: 'ごいばくはつ', slug: 'vocabulary-spurt',
    definition: 'おおむね18〜24ヶ月に、新しい語を急速に取り込み始める時期。開始時期の個人差は大きく、二語文へつながる。',
    see_also: ['理解語彙と産出語彙', '言語のシャワー'] },
  { term: '理解語彙と産出語彙', reading: 'りかいごいとさんしゅつごい', slug: 'receptive-expressive-vocabulary',
    definition: '聞いて分かる語（理解）と、自分で言える語（産出）。理解は産出に先行し、話さない時期にも理解と身ぶりは育っている。',
    see_also: ['語彙爆発', '共同注意'] },
  { term: '拡張（エクスパンション）', reading: 'かくちょう', slug: 'expansion',
    definition: '子の発話に1〜2語だけ足して返す関わり（子「ブーブー」→「あかい ブーブーだね」）。訂正せず、少し上の形を渡すのが要点。',
    see_also: ['サーブ＆リターン', '足場かけ（スキャフォールディング）'] },
  { term: '満足の遅延', reading: 'まんぞくのちえん', slug: 'delayed-gratification',
    definition: '今すぐの報酬を待って、より良い結果を得る力。我慢の強さより、気そらしなどの方略と「約束が守られる環境」に大きく左右される。',
    see_also: ['実行機能（EF）'] },
  { term: '限定された選択', reading: 'げんていされたせんたく', slug: 'limited-choice',
    definition: '大人が選択肢を2〜3に絞り、その中から子に決めさせる関わり。決める負荷を下げつつ自律感を保ち、かんしゃくの予防にもなる。',
    see_also: ['実行機能（EF）'] },
  { term: 'おもちゃのローテーション', reading: 'おもちゃのろーてーしょん', slug: 'toy-rotation',
    definition: '一度に出す玩具を少数に絞り、数週ごとに入れ替える運用。選択肢を減らすことで遊びが深く長くなり、片づけも成立しやすい。',
    see_also: ['ルーズパーツ', 'スクリーンタイム'] },
  { term: '移動系動作と操作系動作', reading: 'いどうけいどうさとそうさけいどうさ', slug: 'locomotor-manipulative',
    definition: '基礎的動作スキルの2系統。走る・跳ぶ・登るなど体を移動させる動作と、投げる・捕る・蹴るなど物に働きかける動作。幼児期は上手さより種類を増やす。',
    see_also: ['基礎的動作スキル（FMS）', 'ABC（運動）'] },
  { term: '身体図式', reading: 'しんたいずしき', slug: 'body-schema',
    definition: '自分の体の位置・大きさ・動きについての脳内の地図。道具を使うとき、脳は道具の先端まで体の一部のように扱う（図式の拡張）。',
    see_also: ['固有感覚', '感覚統合'] },
  { term: '1対1対応', reading: 'いちたいいちたいおう', slug: 'one-to-one-correspondence',
    definition: '物と物、物と数詞を一つずつ対応させること。「一人に一つ配る」がその体験で、数唱の暗記より数の意味の核心にある。',
    see_also: ['数量感覚', '基数性'] },
  { term: '分類（カテゴリー化）', reading: 'ぶんるい', slug: 'classification',
    definition: '色・形・用途などの属性で物をまとめる働き。「同じ仲間」と判断できることが、数える・語彙を獲得する前提になる。',
    see_also: ['パターン認識', '1対1対応'] },
  { term: 'パターン認識', reading: 'ぱたーんにんしき', slug: 'patterning',
    definition: 'くり返しの規則に気づき、続ける力（赤・青・赤・青…）。代数的思考の萌芽とされ、手拍子や並べる遊びで育つ。',
    see_also: ['分類（カテゴリー化）'] },
  { term: '信号対雑音比（音環境）', reading: 'しんごうたいざつおんひ', slug: 'signal-to-noise',
    definition: '聞きたい音と背景音の比。BGMやつけっぱなしのテレビはこの比を下げ、語の切り出しと弁別を難しくする。',
    see_also: ['言語のシャワー', 'スクリーンタイム'] },
  { term: '感覚過敏・感覚探求', reading: 'かんかくかびん・かんかくたんきゅう', slug: 'sensory-sensitivity',
    definition: '刺激を強く感じすぎる傾向と、強い刺激を自分から求める傾向。感覚ごとに異なることも多く、無理な慣らしより刺激量の調整で合わせる。',
    see_also: ['感覚統合', '気質', '相性（適合の良さ）'] },
  { term: 'プリント・アウェアネス', reading: 'ぷりんとあうぇあねす', slug: 'print-awareness',
    definition: '本は左から開く、文字が意味を持つ、といった書かれた言葉についての気づき。読字の前駆スキルの一つで、読み聞かせの中で自然に育つ。',
    see_also: ['音韻意識', '対話的読み聞かせ'] },
  { term: '多重愛着', reading: 'たじゅうあいちゃく', slug: 'multiple-attachment',
    definition: '子が母・父・祖父母・保育者それぞれと同時に、独立した愛着関係を築くこと。愛着は取り合う有限の資源ではなく、続く関係の本数が資産になる。',
    see_also: ['アタッチメント（愛着）', '安全基地'] },
  { term: '予測可能性', reading: 'よそくかのうせい', slug: 'predictability',
    definition: '次に何が起きるか子が見通せること。ストレス反応を下げ、切り替えの抵抗を減らす。時刻の厳密さより、順序と関わり方の一定さで作られる。',
    see_also: ['毒性ストレス', '移行（トランジション）'] },
  { term: '移行（トランジション）', reading: 'いこう', slug: 'transition',
    definition: '遊びを終える・家を出る・入浴する・寝るなど、場面が切り替わる瞬間。一日で最も荒れやすく、予告・儀式・「次」の提示で負荷を下げられる。',
    see_also: ['予測可能性', '情動調整'] },
  { term: '父親の産後うつ', reading: 'ちちおやのさんごうつ', slug: 'paternal-depression',
    definition: '出産後の時期に父親が経験する抑うつ状態（おおむね8〜10%程度と報告）。落ち込みよりいらだち・引きこもり・飲酒の増加として出やすい。',
    see_also: ['毒性ストレス'] },
  { term: '保育の質', reading: 'ほいくのしつ', slug: 'childcare-quality',
    definition: '担当者の安定性・大人一人あたりの子どもの数・応答的な関わり・言葉かけの豊かさなどで捉える指標。在園時間の長短より、この質のほうが結果と関連する。',
    see_also: ['多重愛着', 'サーブ＆リターン'] },
];
