// 参考文献・一次情報源。Opusは各主張に紐づく出典を追記する。
export default [
  { slug: 'harvard-cdc', authors: 'Center on the Developing Child', year: 2016,
    title: 'From Best Practices to Breakthrough Impacts', org: 'Harvard University',
    url: 'https://developingchild.harvard.edu/', note: 'サーブ＆リターン・毒性ストレス・脳の建築の一次情報源', tags: ['serve-return', 'plasticity', 'stress'] },
  { slug: 'nsc-brain', authors: 'National Scientific Council on the Developing Child', year: 2007,
    title: 'The Science of Early Childhood Development', org: 'Harvard University',
    url: 'https://developingchild.harvard.edu/', note: '早期発達科学の総説', tags: ['plasticity', 'critical-periods'] },
  { slug: 'aap-media', authors: 'American Academy of Pediatrics', year: 2016,
    title: 'Media and Young Minds (Policy Statement)', org: 'Pediatrics',
    url: 'https://publications.aap.org/', note: '2歳未満のスクリーン・ビデオデフィシットの指針', tags: ['screen', 'language'] },
  { slug: 'diamond-ef', authors: 'Diamond, A.', year: 2013,
    title: 'Executive Functions', org: 'Annual Review of Psychology',
    url: '', note: '実行機能の定義と発達・介入の総説', tags: ['executive-function'] },
  { slug: 'moffitt-selfcontrol', authors: 'Moffitt, T. E., et al.', year: 2011,
    title: 'A gradient of childhood self-control predicts health, wealth, and public safety', org: 'PNAS',
    url: '', note: 'ダニーデン研究。幼児期の自己制御が広範な人生の結果を予測', tags: ['executive-function'] },
  { slug: 'hart-risley', authors: 'Hart, B. & Risley, T.', year: 1995,
    title: 'Meaningful Differences in the Everyday Experience of Young American Children', org: 'Brookes',
    url: '', note: '語彙格差研究。効果量には後年の再検討・批判もある点に留意', tags: ['language'] },
  { slug: 'whitehurst-dialogic', authors: 'Whitehurst, G. J., et al.', year: 1988,
    title: 'Accelerating language development through picture book reading', org: 'Developmental Psychology',
    url: '', note: '対話的読み聞かせの効果の実証', tags: ['literacy', 'language'] },
  { slug: 'lamb-father', authors: 'Lamb, M. E. (Ed.)', year: 2010,
    title: 'The Role of the Father in Child Development (5th ed.)', org: 'Wiley',
    url: '', note: '父親関与研究の標準的総説', tags: ['fathers'] },
  { slug: 'aap-sports-specialization', authors: 'American Academy of Pediatrics — Council on Sports Medicine', year: 2016,
    title: 'Sports Specialization and Intensive Training in Young Athletes', org: 'Pediatrics',
    url: '', note: '早期スポーツ特化のリスク', tags: ['gross-motor'] },
  { slug: 'lengua-fmS', authors: 'Lubans, D. R., et al.', year: 2010,
    title: 'Fundamental Movement Skills in Children and Adolescents', org: 'Sports Medicine',
    url: '', note: '基礎的動作スキルと健康・後の身体活動の関連', tags: ['gross-motor'] },
  { slug: 'romeo-conversation', authors: 'Romeo, R. R., et al.', year: 2018,
    title: 'Beyond the 30-Million-Word Gap: Children’s Conversational Exposure', org: 'Psychological Science',
    url: '', note: '語数より会話のやりとり回数が脳と言語に効くことを示した研究', tags: ['language'] },
  { slug: 'ginsburg-play', authors: 'Ginsburg, K. R. (AAP)', year: 2007,
    title: 'The Importance of Play in Promoting Healthy Child Development', org: 'Pediatrics',
    url: '', note: '自由な遊びの発達的価値に関するAAP報告', tags: ['play'] },
  { slug: 'paquette-activation', authors: 'Paquette, D.', year: 2004,
    title: 'Theorizing the Father-Child Relationship: Activation Relationship', org: 'Human Development',
    url: '', note: '父親の「賦活（探索を促す）関係」の理論', tags: ['fathers'] },
  { slug: 'kuhl-social', authors: 'Kuhl, P. K., et al.', year: 2003,
    title: 'Foreign-language experience in infancy: Effects of short-term exposure', org: 'PNAS',
    url: '', note: '乳児の外国語音の学習は「生身の人」でのみ生じ、動画・音声では生じないことを示した', tags: ['language', 'bilingual'] },
  { slug: 'werker-narrowing', authors: 'Werker, J. F. & Tees, R. C.', year: 1984,
    title: 'Cross-language speech perception: Evidence for perceptual reorganization', org: 'Infant Behavior & Development',
    url: '', note: '生後1年での音韻知覚の絞り込み（perceptual narrowing）の古典', tags: ['language', 'sensory'] },
  { slug: 'bialystok-bilingual', authors: 'Bialystok, E.', year: 2017,
    title: 'The bilingual adaptation: How minds accommodate experience', org: 'Psychological Bulletin',
    url: '', note: 'バイリンガルの認知的影響のレビュー。効果は文脈依存で過度な一般化に注意', tags: ['bilingual', 'executive-function'] },
  { slug: 'nichd-scdc', authors: 'NICHD Early Child Care Research Network', year: 2006,
    title: 'The NICHD Study of Early Child Care and Youth Development', org: 'NIH',
    url: '', note: '保育の質と発達の大規模縦断研究。「母親専属」でなく関係の質が要点', tags: ['attachment', 'fathers'] },
  { slug: 'pate-preschool-pa', authors: 'Pate, R. R., et al.', year: 2019,
    title: 'Physical Activity in Early Childhood', org: 'Journal of Pediatrics / WHO guidelines',
    url: 'https://www.who.int/', note: '乳幼児の身体活動ガイドライン（WHO 0-5歳）の基礎', tags: ['gross-motor'] },
  { slug: 'zero-to-three', authors: 'ZERO TO THREE', year: 2016,
    title: 'Tuning In: Parents of Young Children Speak Up', org: 'ZERO TO THREE',
    url: 'https://www.zerotothree.org/', note: '乳幼児の発達に関する保護者向けエビデンスの実務的まとめ', tags: ['plasticity', 'social-emotional'] },
  { slug: 'thomas-chess', authors: 'Thomas, A., & Chess, S.', year: 1977,
    title: 'Temperament and Development', org: 'Brunner/Mazel',
    url: '', note: '気質の古典的類型と「相性（goodness of fit）」の概念の出典', tags: ['social-emotional', 'temperament'] },
  { slug: 'belsky-susceptibility', authors: 'Belsky, J., & Pluess, M.', year: 2009,
    title: 'Beyond diathesis stress: Differential susceptibility to environmental influences', org: 'Psychological Bulletin',
    url: '', note: '敏感な子ほど環境の良し悪しの影響を受けやすいという差次感受性の総説（検証途上）', tags: ['social-emotional', 'temperament'] },
  { slug: 'gershoff-punishment', authors: 'Gershoff, E. T., & Grogan-Kaylor, A.', year: 2016,
    title: 'Spanking and child outcomes: Old controversies and new meta-analyses', org: 'Journal of Family Psychology',
    url: '', note: '体罰の効果の乏しさと害の方向の関連を示すメタ分析（因果は交絡に留意）', tags: ['discipline', 'social-emotional'] },
  { slug: 'nelp-literacy', authors: 'National Early Literacy Panel', year: 2008,
    title: 'Developing Early Literacy: Report of the National Early Literacy Panel', org: 'NICHD / National Center for Family Literacy',
    url: '', note: '音韻意識など就学前リテラシー前駆スキルと後の読字の関連', tags: ['literacy'] },
  { slug: 'pruden-spatial-language', authors: 'Pruden, S. M., Levine, S. C., & Huttenlocher, J.', year: 2011,
    title: "Children's spatial thinking: Does talk about the spatial world matter?", org: 'Developmental Science',
    url: '', note: '親の空間語の多さが子の空間認知と関連することを示す研究', tags: ['math-spatial'] },
  { slug: 'lillard-pretend', authors: 'Lillard, A. S., et al.', year: 2013,
    title: "The impact of pretend play on children's development: A review of the evidence", org: 'Psychological Bulletin',
    url: '', note: 'ふり遊びと発達の関連を批判的に整理（多くは相関で因果は慎重に）', tags: ['play', 'executive-function'] },
  { slug: 'nsf-sleep-duration', authors: 'Hirshkowitz, M., et al.', year: 2015,
    title: "National Sleep Foundation's sleep time duration recommendations", org: 'Sleep Health',
    url: '', note: '月齢・年齢ごとの総睡眠時間の推奨レンジ（幅のある目安）', tags: ['sleep'] },
  { slug: 'gunderson-praise', authors: 'Gunderson, E. A., et al.', year: 2013,
    title: "Parent praise to 1- to 3-year-olds predicts children's motivational frameworks 5 years later", org: 'Child Development',
    url: '', note: '1〜3歳期の過程ほめの割合が5年後の挑戦志向を予測した縦断研究', tags: ['social-emotional', 'executive-function'] },
];
