// 神話カード。verdict: false | mostly-false | mixed | oversold
export default [
  {
    slug: 'windows-close', title: '「3歳までにやらないと手遅れ」', evidence: 'A',
    claim: '発達の窓は3歳で閉じ、逃すと取り返せない。', verdict: 'mostly-false',
    reality: '本物の臨界期は視覚や第一言語の音韻などごく一部。語彙・数量・運動・自己制御など学業やスポーツに効く高次能力の窓は一生開いている。',
    harm: '親の不安を煽り、詰め込みや高額教材の購入に走らせる。',
    instead: '締切ではなく"応答的で豊かな日常"の積み重ねを。焦らず土台7原則を回す。',
    related: ['/science/03-critical-periods/'], updated: '2026-07-06',
  },
  {
    slug: 'flashcards-genius', title: '「フラッシュカードで天才になる」', evidence: 'B',
    claim: '大量のフラッシュカードで暗記させれば知能が高まる。', verdict: 'oversold',
    reality: '一時的に単語や事実を覚えても、汎用的な知能や後の学業成績が上がるという確かな証拠はない。乳幼児の学びは受動的暗記でなく双方向のやりとりで進む。',
    harm: '双方向のやりとりの時間を奪い、"できた/できない"の評価で関係を損ないうる。',
    instead: 'カードを見せるより、実物を一緒に触り、名づけ、会話する（サーブ＆リターン）。',
    related: ['/science/05-serve-return/', '/domains/language/'], updated: '2026-07-06',
  },
  {
    slug: 'baby-videos', title: '「知育DVD・動画で賢くなる」', evidence: 'A',
    claim: '乳児向けの知育動画で言語や知能が伸びる。', verdict: 'false',
    reality: '2歳未満では動画から言語をほとんど学べない（ビデオ・デフィシット）。むしろ視聴時間が長いほど言語発達に不利という所見がある。学ぶのは生身の応答から。',
    harm: '対人的やりとりの時間を置き換え、言語発達をむしろ妨げうる。',
    instead: '2歳未満は原則スクリーンを言語の代わりにしない。ビデオ通話（祖父母等）は例外的にやりとりが成立しうる。',
    related: ['/environment/', '/domains/language/'], updated: '2026-07-06',
  },
  {
    slug: 'early-reading', title: '「早く文字を教えるほど賢い」', evidence: 'B',
    claim: '3歳前から読み書きを先取りさせると学業で有利。', verdict: 'mostly-false',
    reality: '早期の文字習得が長期の読解力や学業で優位を生むという証拠は弱い。読解の土台は文字ドリルより、話し言葉の豊かさ・音韻意識・読み聞かせ。',
    harm: '嫌になれば逆効果。楽しさより訓練になると読書嫌いを生みうる。',
    instead: '文字ドリルより対話的読み聞かせと会話。文字は子が興味を持ってからで十分間に合う。',
    related: ['/domains/literacy/', '/domains/language/'], updated: '2026-07-06',
  },
  {
    slug: 'mozart-effect', title: '「モーツァルトを聴かせると頭が良くなる」', evidence: 'A',
    claim: 'クラシックを聴かせるだけで乳児の知能が上がる。', verdict: 'false',
    reality: '"モーツァルト効果"は成人の一時的な空間課題成績の話が誇張されたもので、乳児の知能を高める証拠はない。ただし"自分で歌う・演奏する・リズムに動く"能動的な音楽体験には別の価値がある。',
    harm: '受動的なBGMを"知育"と誤解し、能動的な関わりを軽視させる。',
    instead: '聴かせるより一緒に歌う・手拍子する・踊る。能動的音楽体験を（音楽ドメイン参照）。',
    related: ['/domains/music/'], updated: '2026-07-06',
  },
  {
    slug: 'early-specialization', title: '「早く一つの競技に絞るほど伸びる」', evidence: 'B',
    claim: '幼児期から単一スポーツに特化させると将来有利。', verdict: 'mostly-false',
    reality: '幼児期の早期特化は、多様な動作経験の不足・怪我・燃え尽きのリスクを上げる。将来の運動能力の土台は多様な遊びと基礎動作スキル。',
    harm: '偏った身体の使い方・オーバーユース障害・運動嫌い。',
    instead: '競技より多様な遊び。走る・跳ぶ・投げる・登るを幅広く（ABC：敏捷性・バランス・協応）。',
    related: ['/domains/gross-motor/'], updated: '2026-07-06',
  },
  {
    slug: 'spoiling-babies', title: '「抱き癖がつくと甘えん坊になる」', evidence: 'A',
    claim: '泣くたびに抱くと自立できない甘えん坊になる。', verdict: 'false',
    reality: '0〜1歳で泣きに応じることは依存を作らず、安定した愛着＝安全基地を作る。十分に安心を得た子ほどよく自立し、探索する。',
    harm: '応答をためらわせ、愛着形成の機会を減らす。',
    instead: '乳児期の泣きには応じてよい。一貫した応答が自立の土台。',
    related: ['/science/04-attachment/'], updated: '2026-07-06',
  },
];
