// 月齢ロードマップの空き帯を補完（3-6, 9-12, 18-24, 24-30, 30-36）。
// milestones.mjs（0-3,6-9,12-18のシード）とは別ファイル。時期は目安、個人差大。
export default [
  // ---- 3-6ヶ月 ----
  {
    ageBand: '3-6', domain: 'gross-motor', slug: '3-6-gross-motor',
    title: '寝返り〜支え座り', evidence: 'B', typical_range: '寝返りは4〜6ヶ月ごろ',
    emerges: ['寝返り', '支えれば座る', '足で床を蹴る'],
    high_leverage: ['自由に動ける床時間', 'うつ伏せ遊びの継続'],
    father_edge: '手の届く所に玩具を置き、寝返り・リーチを引き出す。',
    red_flags: ['首すわりが見られない', '極端に体が硬い/柔らかい'],
    related: ['/activities/floor-freedom/', '/domains/gross-motor/', '/domains/gross-motor/tummy-time/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'sensory', slug: '3-6-sensory',
    title: '手と口で世界を調べる', evidence: 'B', typical_range: '—',
    emerges: ['物に手を伸ばす', '口に持っていって確かめる', '色・動きへの興味'],
    high_leverage: ['安全で多様な感触の物を渡す', '多感覚で名づける'],
    father_edge: '散歩で光・風・音の実況。多感覚シャワーを浴びせる。',
    red_flags: ['音や光に全く反応しない', '目で追わない'],
    related: ['/domains/sensory/', '/activities/naming-walk/', '/domains/sensory/sensory-preferences/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'social-emotional', slug: '3-6-social',
    title: '笑いと情動の同調', evidence: 'B', typical_range: '声を出して笑うのは3〜4ヶ月ごろ',
    emerges: ['声を出して笑う', '養育者との情動のやりとり', '人を見分ける'],
    high_leverage: ['表情豊かに応じる', 'いないいないばあ'],
    father_edge: '大きな表情と声で笑いを引き出す遊びは父が得意。',
    red_flags: ['あやしても笑わない/反応が極端に乏しい'],
    related: ['/domains/social-emotional/', '/activities/peekaboo/'], updated: '2026-07-06',
  },
  // ---- 9-12ヶ月 ----
  {
    ageBand: '9-12', domain: 'fine-motor', slug: '9-12-fine-motor',
    title: 'ピンサーグリップ', evidence: 'B', typical_range: '親指と人差し指でつまむのは9〜12ヶ月',
    emerges: ['小さな物を指先でつまむ', '両手で持ち替える', '容器に入れる/出す'],
    high_leverage: ['入れる・出す遊び', 'つまむ機会を作る（安全サイズで）'],
    father_edge: '大きめのボルトやカラビナなど父の道具箱が題材（誤飲サイズ注意）。',
    red_flags: ['物に手を伸ばさない', '手を使おうとしない'],
    related: ['/activities/container-play/', '/domains/fine-motor/', '/domains/fine-motor/pincer-grip/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'language', slug: '9-12-language',
    title: '指さしと初語の入り口', evidence: 'B', typical_range: '指さし要求は9〜14ヶ月、初語は約12ヶ月',
    emerges: ['指さしで要求・共有', '簡単な言葉の理解（ちょうだい等）', '喃語が言葉らしく'],
    high_leverage: ['指さし応答', 'ことばの拡張'],
    father_edge: '子が指さすたびに立ち止まり名づける余裕を持つ。',
    red_flags: ['指さしが出ない', '名前や声への反応が乏しい'],
    related: ['/activities/point-and-respond/', '/domains/language/', '/domains/language/parentese/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'executive-function', slug: '9-12-ef',
    title: '意図と手段（因果の理解）', evidence: 'C', typical_range: '—',
    emerges: ['布を引いて物を取る等の手段-目的', '隠した物を探す', '簡単な模倣'],
    high_leverage: ['かくれんぼ（物さがし）', '模倣を促す遊び'],
    father_edge: '「どうやったら取れる？」と少しだけ難しい状況を作り足場をかける。',
    red_flags: [],
    related: ['/activities/hide-and-seek-objects/', '/domains/executive-function/', '/domains/executive-function/self-regulation-play/'], updated: '2026-07-06',
  },
  // ---- 18-24ヶ月 ----
  {
    ageBand: '18-24', domain: 'language', slug: '18-24-language',
    title: '語彙爆発と二語文', evidence: 'B', typical_range: '語彙爆発〜二語文は18〜24ヶ月ごろ',
    emerges: ['語彙が急増', '二語文（「わんわん いた」）', '簡単な指示に従う'],
    high_leverage: ['対話的読み聞かせ', 'ことばの拡張', '絵本でお話づくり'],
    father_edge: '父の語彙・話題を持ち込み、言葉の幅を広げる。',
    red_flags: ['24ヶ月で二語文の兆しがなく語彙が極端に少ない', '理解も乏しい'],
    related: ['/activities/expand-and-extend/', '/domains/language/', '/domains/language/word-explosion/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'gross-motor', slug: '18-24-gross-motor',
    title: '走る・登る・蹴る', evidence: 'B', typical_range: '走行・階段は個人差大',
    emerges: ['走る', '低い段を登る', 'ボールを蹴る/投げる（粗い形）'],
    high_leverage: ['クッション障害物コース', 'ボール転がし・受け渡し'],
    father_edge: '公園の低い遊具や外遊びで多様な動きを幅広く。',
    red_flags: ['歩行が安定しない', '動きの左右差が続く'],
    related: ['/activities/obstacle-crawl/', '/domains/gross-motor/', '/domains/gross-motor/ball-and-locomotion/', '/domains/gross-motor/risky-play/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'play', slug: '18-24-play',
    title: 'ふり遊びの芽生え', evidence: 'B', typical_range: '見立て遊びは18ヶ月ごろから',
    emerges: ['物を別の物に見立てる', '人形の世話のまね', '大人の模倣遊び'],
    high_leverage: ['ごっこ遊び（見立て）', 'オープンエンドな玩具'],
    father_edge: '父も本気で役に入る。恥ずかしがらず一緒になりきる。',
    red_flags: ['模倣やふりが全く見られない'],
    related: ['/activities/pretend-play/', '/domains/play/', '/domains/play/open-ended-play/', '/domains/play/pretend-play/'], updated: '2026-07-06',
  },
  // ---- 24-30ヶ月 ----
  {
    ageBand: '24-30', domain: 'executive-function', slug: '24-30-ef',
    title: '自己主張と、待つ力の芽', evidence: 'B', typical_range: 'イヤイヤ期の中心は2歳前後',
    emerges: ['強い自己主張（イヤイヤ）', '短い順番待ち', '簡単なルールのある遊び'],
    high_leverage: ['「待つ」遊び', 'ダンス＆ストップ', '感情の実況'],
    father_edge: '「我慢」を罰でなくゲームにする。感情を受け止めてから対処。',
    red_flags: [],
    related: ['/activities/waiting-games/', '/domains/executive-function/', '/domains/executive-function/waiting-and-turn-taking/', '/domains/executive-function/attention-and-focus/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'math-spatial', slug: '24-30-math',
    title: '数え始め・大小・分類', evidence: 'C', typical_range: '数唱の入り口は2歳ごろ',
    emerges: ['「いち・に・さん」の数唱', '大小・多少の比較', '色や形で分ける'],
    high_leverage: ['生活の中で数える', '仲間分け（分類あそび）', '積む・入れ子'],
    father_edge: '階段・おやつ・お手伝いに数と比較を混ぜる。',
    red_flags: [],
    related: ['/activities/count-everyday/', '/domains/math-spatial/', '/domains/math-spatial/number-sense/', '/domains/math-spatial/spatial-thinking/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'social-emotional', slug: '24-30-social',
    title: '感情のことばと共感の芽', evidence: 'B', typical_range: '—',
    emerges: ['感情を言葉にし始める', '他者の気持ちへの関心', '簡単ななぐさめ'],
    high_leverage: ['気持ちの実況（感情のことば化）', '絵本で気持ちを考える'],
    father_edge: '父自身が感情を言葉にし、落ち着くモデルを見せる。',
    red_flags: ['視線・やりとり・関わりの乏しさが続く'],
    related: ['/activities/emotion-labeling/', '/domains/social-emotional/', '/domains/social-emotional/tantrums/', '/domains/social-emotional/emotion-coaching/'], updated: '2026-07-06',
  },
  // ---- 30-36ヶ月 ----
  {
    ageBand: '30-36', domain: 'language', slug: '30-36-language',
    title: '会話と質問期', evidence: 'B', typical_range: '3語以上の文・質問は3歳前後',
    emerges: ['多語文で話す', '「なぜ？」の質問', '簡単な物語の理解と再話'],
    high_leverage: ['対話的読み聞かせ', '絵本でお話づくり'],
    father_edge: '「なぜ」に付き合い、一緒に考える。答えを急がず対話を楽しむ。',
    red_flags: ['3歳で言葉が非常に少ない', '会話が成立しない', '一度できたことの退行'],
    related: ['/activities/wordless-storytelling/', '/domains/language/', '/domains/language/word-explosion/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'gross-motor', slug: '30-36-gross-motor',
    title: 'ジャンプ・バランスの向上', evidence: 'B', typical_range: '両足ジャンプは2〜3歳',
    emerges: ['両足でジャンプ', '片足立ちの芽', 'つま先立ち・その場回転'],
    high_leverage: ['ダンス＆ストップ', '多様な運動遊び（ABC）'],
    father_edge: '競技に絞らず、走る・跳ぶ・登る・投げるを幅広く（早期特化しない）。',
    red_flags: ['歩行・粗大運動の明確な遅れや退行'],
    related: ['/activities/dance-freeze/', '/domains/gross-motor/', '/domains/gross-motor/ball-and-locomotion/', '/domains/gross-motor/risky-play/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'executive-function', slug: '30-36-ef',
    title: 'ごっこの複雑化と切り替え', evidence: 'B', typical_range: '—',
    emerges: ['筋のあるごっこ遊び', 'ルールの切り替え', '短い指示の記憶と実行'],
    high_leverage: ['ごっこ遊び（見立て）', '仲間分け（基準の切り替え）', 'ダンス＆ストップ'],
    father_edge: '遊びの中で少しだけ難しいルールを足し、足場をかける。',
    red_flags: [],
    related: ['/activities/pretend-play/', '/domains/executive-function/', '/domains/executive-function/waiting-and-turn-taking/', '/domains/executive-function/attention-and-focus/'], updated: '2026-07-06',
  },
];
