// 月齢ロードマップ補完 第2弾：帯×ドメインの空きマスを埋める。
// （既存: milestones.mjs / roadmap-fill.mjs と slug 重複しないこと）
export default [
  // ---- 0-3ヶ月 ----
  {
    ageBand: '0-3', domain: 'sensory', slug: '0-3-sensory',
    title: '見つめる・追う・音に向く', evidence: 'B', typical_range: '追視は1〜3ヶ月で滑らかに',
    emerges: ['顔をじっと見る（20〜30cmが見やすい）', '動く物を目で追う', '音の方へ顔を向ける'],
    high_leverage: ['顔を近づけてゆっくり動く「追視あそび」', 'コントラストの強い絵・模様を見せる'],
    father_edge: '抱っこの位置＝ちょうど見える距離。父の顔そのものが最初の教材。',
    red_flags: ['光や音に全く反応しない', '目が合う気配がない（3ヶ月ごろ）'],
    related: ['/domains/sensory/', '/science/03-critical-periods/', '/domains/sensory/sensory-preferences/'], updated: '2026-07-06',
  },
  {
    ageBand: '0-3', domain: 'music', slug: '0-3-music',
    title: '声とリズムを浴びる', evidence: 'B', typical_range: '—',
    emerges: ['養育者の声を聞き分ける', '抑揚のある声への注意', '揺れ・リズムで落ち着く'],
    high_leverage: ['子守唄・鼻歌を毎日（上手さ不要）', '抱っこでゆっくり揺れながら歌う'],
    father_edge: '低い声は子宮内でも届いていた音域。父の歌・ハミングは特別な安心材料。',
    red_flags: [],
    related: ['/domains/music/', '/activities/singing-daily/', '/domains/music/listening-environment/'], updated: '2026-07-06',
  },
  // ---- 3-6ヶ月 ----
  {
    ageBand: '3-6', domain: 'language', slug: '3-6-language',
    title: 'クーイングから喃語へ', evidence: 'B', typical_range: '喃語（バババ等）は4〜6ヶ月ごろから',
    emerges: ['「あーうー」（クーイング）', '声のやりとりを楽しむ', '笑い声・声の実験'],
    high_leverage: ['声が出たらまねして返す（音のラリー）', 'parentese（抑揚豊かな語りかけ）'],
    father_edge: '子の声をまねて返すだけで会話の原型になる。通勤前後の5分でも成立。',
    red_flags: ['声をほとんど出さない', '6ヶ月で音への反応が乏しい'],
    related: ['/activities/parentese/', '/science/05-serve-return/', '/domains/language/parentese/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'fine-motor', slug: '3-6-fine-motor',
    title: 'リーチングと把握', evidence: 'B', typical_range: '狙って手を伸ばすのは3〜5ヶ月ごろ',
    emerges: ['物に狙って手を伸ばす', '掴んで口へ運ぶ', '両手を体の正面で合わせる'],
    high_leverage: ['握りやすい玩具を少し遠くに置く', '素材の違う物を握らせる'],
    father_edge: '「あと少しで届く」距離の調整役。取れた瞬間を一緒に喜ぶ。',
    red_flags: ['5〜6ヶ月で物に手を伸ばす気配がない'],
    related: ['/domains/fine-motor/', '/activities/floor-freedom/'], updated: '2026-07-06',
  },
  // ---- 6-9ヶ月 ----
  {
    ageBand: '6-9', domain: 'fine-motor', slug: '6-9-fine-motor',
    title: '持ち替え・打ち合わせ', evidence: 'B', typical_range: '手から手への持ち替えは6〜8ヶ月',
    emerges: ['手から手へ持ち替える', '両手の物を打ち合わせる', '熊手のように掻き寄せる'],
    high_leverage: ['両手に一つずつ持たせる', '叩くと音が出る物で因果を体験'],
    father_edge: 'トントン打ち合わせを一緒に。音のやりとりはリズムあそびの入り口。',
    red_flags: ['片手しか使わない状態が続く（明確な左右差）'],
    related: ['/domains/fine-motor/', '/activities/rhythm-tapping/', '/domains/fine-motor/pincer-grip/'], updated: '2026-07-06',
  },
  {
    ageBand: '6-9', domain: 'social-emotional', slug: '6-9-social',
    title: '人見知りと安全基地', evidence: 'A', typical_range: '人見知り・分離不安は6〜9ヶ月ごろから',
    emerges: ['特定の人への愛着が明確に', '知らない人への警戒（人見知り）', '养育者の表情をうかがう（社会的参照の芽）'],
    high_leverage: ['不安な場面でしっかり受け止める', 'いないいないばあ（消えても戻る、の練習）'],
    father_edge: '人見知りで父が拒まれても正常な発達のサイン。腐らず淡々と関わり続けることが効く。',
    red_flags: ['特定の人への愛着行動がまったく見られない'],
    related: ['/science/04-attachment/', '/activities/peekaboo/', '/domains/social-emotional/separation-anxiety/'], updated: '2026-07-06',
  },
  {
    ageBand: '6-9', domain: 'sensory', slug: '6-9-sensory',
    title: '触って落として確かめる', evidence: 'B', typical_range: '—',
    emerges: ['物を振る・叩く・落とすで性質を調べる', '食感・温度の違いへの反応', '落ちた物を目で追う'],
    high_leverage: ['「落とす→拾って返す」に付き合う（実験に見えるのは学習）', '素材・音の違う物を用意'],
    father_edge: '何度落とされても拾って返す根気担当。「落ちたね、ゴトン！」と実況を添える。',
    red_flags: [],
    related: ['/domains/sensory/', '/activities/container-play/', '/domains/sensory/sensory-preferences/'], updated: '2026-07-06',
  },
  // ---- 9-12ヶ月 ----
  {
    ageBand: '9-12', domain: 'gross-motor', slug: '9-12-gross-motor',
    title: 'はいはい・つかまり立ち・伝い歩き', evidence: 'B', typical_range: 'つかまり立ちは8〜11ヶ月ごろ（幅大）',
    emerges: ['はいはいの加速', 'つかまり立ち', '伝い歩き'],
    high_leverage: ['はいはいで追いかけっこ', 'つかまれる家具の安全な配置', '階段や坂の探索（見守りつつ）'],
    father_edge: '床に寝そべって同じ目線ではいはい競争。父が"動く障害物"になる。',
    red_flags: ['12ヶ月で支えても立とうとしない', '移動の意欲が極端に乏しい'],
    related: ['/activities/obstacle-crawl/', '/science/09-movement/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'social-emotional', slug: '9-12-social',
    title: '社会的参照 — 顔色で世界を測る', evidence: 'A', typical_range: '社会的参照は9〜12ヶ月ごろ明確に',
    emerges: ['新しい物・人の前で養育者の表情を確認する', '「だめ」の声のトーンを理解し始める', 'バイバイ・ぱちぱちなど社会的しぐさ'],
    high_leverage: ['挑戦場面で穏やかな笑顔を返す（安心のGOサイン）', '社会的しぐさのやりとり'],
    father_edge: '父の落ち着いた表情が「やってみていい」の合図になる。過剰に驚かない・慌てない。',
    red_flags: ['視線のやりとり・表情の参照がまったくない'],
    related: ['/fathers-edge/03-pushing-secure-base/', '/domains/social-emotional/', '/domains/social-emotional/separation-anxiety/'], updated: '2026-07-06',
  },
  // ---- 12-18ヶ月 ----
  {
    ageBand: '12-18', domain: 'executive-function', slug: '12-18-ef',
    title: '試行錯誤と簡単なルール', evidence: 'B', typical_range: '—',
    emerges: ['やり方を変えて試す（形合わせ等）', '「ちょうだい/どうぞ」の往復', '簡単な禁止の理解（守れるとは限らない）'],
    high_leverage: ['形合わせ・型はめパズル', '「どうぞ/ちょうだい」の交換あそび'],
    father_edge: 'すぐ答えを見せず、試行錯誤を3回待ってから最小限のヒント。',
    red_flags: [],
    related: ['/domains/executive-function/', '/activities/errand-missions/', '/domains/executive-function/self-regulation-play/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'fine-motor', slug: '12-18-fine-motor',
    title: 'なぐり書き・積む・スプーン', evidence: 'B', typical_range: '積み木2〜4個は12〜18ヶ月ごろ',
    emerges: ['クレヨンでなぐり書き', '積み木を2〜4個積む', 'スプーンへの挑戦（こぼしながら）'],
    high_leverage: ['大きな紙と太いクレヨン', '積む・入れ子あそび', '自分で食べる機会（散らかり許容）'],
    father_edge: '「上手に描けたね」より「いっぱい描いたね！」——過程を実況する係。',
    red_flags: ['道具（スプーン・クレヨン）に全く興味を示さない状態が続く'],
    related: ['/activities/stacking-nesting/', '/domains/fine-motor/', '/domains/fine-motor/pincer-grip/', '/domains/fine-motor/scribble-to-writing/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'play', slug: '12-18-play',
    title: '道具としての遊び・運ぶ・出し入れ', evidence: 'B', typical_range: '—',
    emerges: ['物を目的をもって使う（コップで飲むふりの芽）', '運ぶ・集める・出し入れの反復', '同じ遊びの繰り返しを好む'],
    high_leverage: ['出し入れできる容器・袋・箱', '「運ぶ仕事」を頼む（洗濯物1枚など）'],
    father_edge: '反復に飽きず付き合う。「またやるの？」ではなく反復こそ学習と心得る。',
    red_flags: [],
    related: ['/activities/container-play/', '/domains/play/', '/domains/play/open-ended-play/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'social-emotional', slug: '12-18-social',
    title: '感情の共有と、かんしゃくの始まり', evidence: 'B', typical_range: '—',
    emerges: ['できた時に養育者を見て喜びを共有', '思い通りにならない時のかんしゃく', '「いや」の意思表示'],
    high_leverage: ['喜びの共有に全力で応じる', '感情のことば化（「悔しかったね」）'],
    father_edge: 'かんしゃくに怒りで返さない。まず気持ちを言葉に、それから切り替えの手伝い。',
    red_flags: ['感情の共有（見て・見せて）がまったくない'],
    related: ['/activities/emotion-labeling/', '/domains/social-emotional/', '/domains/social-emotional/separation-anxiety/', '/domains/social-emotional/emotion-coaching/'], updated: '2026-07-06',
  },
  // ---- 18-24ヶ月 ----
  {
    ageBand: '18-24', domain: 'fine-motor', slug: '18-24-fine-motor',
    title: '積み上げ・めくる・型はめ', evidence: 'B', typical_range: '積み木4〜6個・ページめくりは18〜24ヶ月ごろ',
    emerges: ['積み木を高く積む', '絵本を1枚ずつめくる', '型はめ・大きなビーズ'],
    high_leverage: ['注ぐ・移す（お水の仕事）', '絵本のページめくり係を任せる'],
    father_edge: '崩れた時の「もう一回！」に付き合う。失敗→再挑戦の回路を育てる。',
    red_flags: [],
    related: ['/activities/water-pouring/', '/domains/fine-motor/', '/domains/fine-motor/scribble-to-writing/', '/domains/fine-motor/tool-use/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'social-emotional', slug: '18-24-social',
    title: '自我の芽生えと「じぶんで！」', evidence: 'B', typical_range: 'イヤイヤの入り口は18ヶ月ごろから',
    emerges: ['「じぶんで！」の主張', '所有の主張（「〇〇ちゃんの！」）', '鏡の自分がわかる（自己認識）'],
    high_leverage: ['時間が許す限り「じぶんで」をやらせる', '2択で選ばせる（「赤と青、どっち？」）'],
    father_edge: '朝の忙しさで奪いがちな「じぶんで」を、休日の父時間でたっぷり保証する。',
    red_flags: [],
    related: ['/domains/social-emotional/', '/activities/mirror-play/', '/domains/social-emotional/separation-anxiety/', '/domains/social-emotional/tantrums/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'executive-function', slug: '18-24-ef',
    title: '簡単な指示の遂行と切り替え', evidence: 'B', typical_range: '—',
    emerges: ['一段階の指示を確実に遂行', '「おしまい」からの切り替え（練習中）', '順番の概念の芽'],
    high_leverage: ['おつかいミッション（一段階→二段階へ）', '「待つ」遊びを短く'],
    father_edge: '切り替えは予告が9割（「あと1回滑ったらおしまいね」）。急な中断を避ける。',
    red_flags: ['簡単な指示・言葉かけへの反応が一貫して乏しい'],
    related: ['/activities/errand-missions/', '/activities/waiting-games/', '/domains/executive-function/self-regulation-play/', '/domains/executive-function/waiting-and-turn-taking/'], updated: '2026-07-06',
  },
  // ---- 24-30ヶ月 ----
  {
    ageBand: '24-30', domain: 'gross-motor', slug: '24-30-gross-motor',
    title: '両足ジャンプ・ボールを蹴る', evidence: 'B', typical_range: '両足ジャンプは24〜30ヶ月ごろ',
    emerges: ['その場で両足ジャンプ', '狙ってボールを蹴る', '階段を手すりで昇降'],
    high_leverage: ['低い段からのジャンプ遊び（手をつないで）', 'まてまて（追いかけっこ）'],
    father_edge: '「せーの、ジャンプ！」の着地を支える係。成功体験の量産が身体の自信になる。',
    red_flags: ['走れない・極端な転びやすさが続く'],
    related: ['/activities/chase-and-catch/', '/domains/gross-motor/', '/domains/gross-motor/ball-and-locomotion/', '/domains/gross-motor/risky-play/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'language', slug: '24-30-language',
    title: '文が伸びる・質問が始まる', evidence: 'B', typical_range: '—',
    emerges: ['三語文へ', '「これなに？」の質問', '代名詞・助詞の芽'],
    high_leverage: ['「これなに？」に答えて一歩広げる', '写真でおしゃべり（思い出トーク）'],
    father_edge: '同じ質問の繰り返しにも新しい一言を足して返す。質問期は語彙獲得の黄金期。',
    red_flags: ['二語文がまだ見られない場合は相談を検討'],
    related: ['/activities/photo-talk/', '/activities/expand-and-extend/', '/domains/language/word-explosion/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'play', slug: '24-30-play',
    title: 'ごっこの筋書きと並行遊び', evidence: 'B', typical_range: '—',
    emerges: ['2〜3手順のごっこ（注ぐ→飲む→「おいしい」）', '他児のそばで遊ぶ（並行遊び）', 'お気に入りの筋の反復'],
    high_leverage: ['ごっこに役として参加', 'キッチンお手伝い（本物への参加）'],
    father_edge: '客役・患者役など「受けの演技」で子の筋書きを引き出す。',
    red_flags: ['ふり遊びがまったく出ない'],
    related: ['/activities/pretend-play/', '/activities/kitchen-helper/', '/domains/play/open-ended-play/', '/domains/play/pretend-play/'], updated: '2026-07-06',
  },
  // ---- 30-36ヶ月 ----
  {
    ageBand: '30-36', domain: 'math-spatial', slug: '30-36-math',
    title: '3までの理解・形・比較', evidence: 'B', typical_range: '「3つちょうだい」が正しくできるのは3歳前後から',
    emerges: ['小さな数の正確な理解（1〜3）', '丸・三角・四角の区別', '長い/短い・重い/軽いの比較'],
    high_leverage: ['「2つちょうだい」の数の実践', '仲間分け・形さがし（「まるいもの、どこ？」）'],
    father_edge: '散歩を「形さがし」「数さがし」の探検に変える。標識・タイヤ・窓——街は教材だらけ。',
    red_flags: [],
    related: ['/activities/count-everyday/', '/activities/sorting-game/', '/domains/math-spatial/number-sense/', '/domains/math-spatial/spatial-thinking/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'social-emotional', slug: '30-36-social',
    title: '友だちへの関心と気持ちの言葉', evidence: 'B', typical_range: '—',
    emerges: ['他児と関わろうとする（貸し借りはまだ難しい）', '「かなしい」「おこってる」など感情語', '簡単な思いやり行動'],
    high_leverage: ['絵本の登場人物の気持ちを一緒に考える', '貸し借りの練習は大人が仲介して成功体験に'],
    father_edge: '「パパ、いま嬉しいよ」と父自身の感情を言葉で開示する。感情語のモデルは効く。',
    red_flags: ['他者への関心が極端に乏しい', 'やりとりの成立しにくさが続く'],
    related: ['/activities/emotion-labeling/', '/domains/social-emotional/', '/domains/social-emotional/tantrums/', '/domains/social-emotional/emotion-coaching/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'fine-motor', slug: '30-36-fine-motor',
    title: '描く形・はさみの入り口・着脱', evidence: 'B', typical_range: '円のまねがきは3歳前後',
    emerges: ['円・線のまねがき', '子ども用はさみの一回切り', '大きなボタン・靴の着脱への挑戦'],
    high_leverage: ['お絵かきの時間を日常に', '着替えの「自分でできる部分」を任せる'],
    father_edge: '不器用でも急かさない。「自分でできた」の総量が就学前の自信を作る。',
    red_flags: [],
    related: ['/domains/fine-motor/', '/activities/kitchen-helper/', '/domains/fine-motor/tool-use/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'play', slug: '30-36-play',
    title: '協同遊びの入り口・ルールのある遊び', evidence: 'B', typical_range: '—',
    emerges: ['簡単なルールのある遊び（かくれんぼ・むっくりくまさん）', '役割のあるごっこ', '「一緒に」作る遊び'],
    high_leverage: ['家族でルール遊び（だるまさんがころんだ等の簡易版）', '積み木やブロックの共同制作'],
    father_edge: 'ルールを守る・負けても大丈夫、を遊びの中で。父がわざと負けて「くやしい〜！でも楽しかった」とモデルを見せる。',
    red_flags: [],
    related: ['/activities/dance-freeze/', '/domains/play/', '/domains/play/open-ended-play/', '/domains/play/pretend-play/'], updated: '2026-07-06',
  },
];
