// 月齢ロードマップ補完 第3弾：残り34マスを充足し、8帯×10ドメイン=80マス完成。
// 低月齢帯の math/literacy 等は「芽」の段階として誠実に記述（誇張しない）。
export default [
  // ================ 0-3ヶ月（+5） ================
  {
    ageBand: '0-3', domain: 'fine-motor', slug: '0-3-fine-motor',
    title: '握って、ゆっくり開いて', evidence: 'B', typical_range: '把握反射から随意的な手へ移行中',
    emerges: ['握る（反射から）', '手をじっと見つめる（ハンドリガード）', '手が口へ'],
    high_leverage: ['指を握らせて話しかける', '軽い布・ガラガラを手に触れさせる'],
    father_edge: '父の太い指は握りやすい鉄棒。握られたら「ぎゅっ、上手」と声を返す。',
    red_flags: [], related: ['/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    ageBand: '0-3', domain: 'math-spatial', slug: '0-3-math',
    title: '量と空間の直感の芽', evidence: 'C', typical_range: '—',
    emerges: ['動くものの軌跡を追う', '「多い/少ない」の大まかな区別（近似数感覚）は生得的に備わる'],
    high_leverage: ['ゆっくり動かして追視させる', 'この時期に特別なことは不要——抱っこで移動する経験自体が空間の入力'],
    father_edge: '抱っこ・ベビーカーでの移動が最初の空間学習。焦って何かをする時期ではない。',
    red_flags: [], related: ['/domains/math-spatial/'], updated: '2026-07-06',
  },
  {
    ageBand: '0-3', domain: 'executive-function', slug: '0-3-ef',
    title: '「落ち着く」を体で学ぶ', evidence: 'B', typical_range: '—',
    emerges: ['なだめられて落ち着く経験', '睡眠と覚醒のリズムの芽'],
    high_leverage: ['泣きに素早く応じてなだめる（自己調整の外部足場）', '予測可能な日課'],
    father_edge: '実行機能の最初の形は「落ち着けること」。父の腕の中で落ち着く経験が、後の自己制御の原型になる。',
    red_flags: [], related: ['/science/06-stress/', '/domains/executive-function/'], updated: '2026-07-06',
  },
  {
    ageBand: '0-3', domain: 'play', slug: '0-3-play',
    title: '顔が最初のおもちゃ', evidence: 'B', typical_range: '—',
    emerges: ['人の顔をじっと見る', '声・表情への反応', 'やりとりの快の芽'],
    high_leverage: ['顔を近づけて表情で遊ぶ', '声のまね返し'],
    father_edge: 'この時期の遊び道具は父の顔と声で十分。玩具はまだ脇役。',
    red_flags: [], related: ['/domains/play/', '/activities/parentese/'], updated: '2026-07-06',
  },
  {
    ageBand: '0-3', domain: 'literacy', slug: '0-3-literacy',
    title: '声の心地よさから始まる', evidence: 'B', typical_range: '—',
    emerges: ['読み手の声への注意', '抑揚・リズムを好む'],
    high_leverage: ['膝で短い絵本を（内容よりも声と密着）', '声色を変えて読む'],
    father_edge: '「本＝父の声と温もり」という最初の連合を作る時期。1日1分でも意味がある。',
    red_flags: [], related: ['/domains/literacy/', '/environment/03-books/'], updated: '2026-07-06',
  },
  // ================ 3-6ヶ月（+5） ================
  {
    ageBand: '3-6', domain: 'math-spatial', slug: '3-6-math',
    title: '距離とリーチの学習', evidence: 'C', typical_range: '—',
    emerges: ['届く/届かないの学習（リーチング）', '物の大きさへの手の調整の芽'],
    high_leverage: ['届きそうな距離に物を置く', '大小の握りやすい物を渡す'],
    father_edge: '「あと少し」の距離設計係。届いた瞬間の達成を一緒に喜ぶ。',
    red_flags: [], related: ['/domains/math-spatial/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'executive-function', slug: '3-6-ef',
    title: '予期と期待 — 「くる、くる…きた！」', evidence: 'B', typical_range: '—',
    emerges: ['日課の流れを予期する', '「いないいない…ばあ」への期待の表情'],
    high_leverage: ['同じ流れの遊びを繰り返し、間で期待させる', '生活の節目を同じ言葉で予告'],
    father_edge: '「3、2、1…たかい！」のカウントで予期を作る。予測できる父は安心の源。',
    red_flags: [], related: ['/activities/peekaboo/', '/domains/executive-function/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'music', slug: '3-6-music',
    title: '声あそびと音の実験', evidence: 'B', typical_range: '—',
    emerges: ['声の高低・大小の実験（自分の声で遊ぶ）', '歌への静聴・体の反応'],
    high_leverage: ['子の声をまねて音のラリー', '膝の上で拍に合わせて軽く揺れる'],
    father_edge: '低い声と高い声の振り幅で笑わせる。父の声域は楽器のひとつ。',
    red_flags: [], related: ['/activities/call-response-song/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'play', slug: '3-6-play',
    title: '繰り返しがおもしろい', evidence: 'B', typical_range: '—',
    emerges: ['同じ遊びの反復を喜ぶ', '揺れ・くすぐりなど体の遊びへの笑い'],
    high_leverage: ['「もう一回」の合図（体の動き・声）を読み取って応じる', '短い体あそびのレパートリーを2〜3個'],
    father_edge: '反復に飽きないのが大人の仕事。子の「もう一回」は学習中のサイン。',
    red_flags: ['あやしても笑いや反応がほとんどない'], related: ['/domains/play/'], updated: '2026-07-06',
  },
  {
    ageBand: '3-6', domain: 'literacy', slug: '3-6-literacy',
    title: '本はまず「触るもの」', evidence: 'B', typical_range: '—',
    emerges: ['本に手を伸ばす・叩く・かじる', '鮮やかな絵への注視'],
    high_leverage: ['布絵本・ボードブックを玩具として自由に', '短く抑揚たっぷりに読む（完読は目標にしない）'],
    father_edge: 'かじられても「本に興味を持った」と喜ぶ。この時期の正しい読書は五感で味わうこと。',
    red_flags: [], related: ['/environment/03-books/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 6-9ヶ月（+4） ================
  {
    ageBand: '6-9', domain: 'math-spatial', slug: '6-9-math',
    title: '「ある/ない」と容器の発見', evidence: 'C', typical_range: '—',
    emerges: ['隠れた物を探し始める（対象の永続性の芽）', '容器の中と外への興味'],
    high_leverage: ['布で隠して見つける遊び', 'カップ・箱への出し入れ'],
    father_edge: '「ないない…あった！」の演出係。消える→現れるの驚きが空間と記憶を育てる。',
    red_flags: [], related: ['/activities/hide-and-seek-objects/', '/domains/math-spatial/'], updated: '2026-07-06',
  },
  {
    ageBand: '6-9', domain: 'music', slug: '6-9-music',
    title: '叩けば鳴る — 音の因果', evidence: 'B', typical_range: '—',
    emerges: ['物を叩いて音を出す', 'リズムに体が揺れる', '好きな歌への反応'],
    high_leverage: ['叩くと鳴る物を用意（鍋・太鼓）', '同じ歌を毎日（レパートリー化）'],
    father_edge: '一緒に叩いて「音のかけあい」に。うるさい時間を数分だけ許容する度量。',
    red_flags: [], related: ['/activities/rhythm-tapping/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '6-9', domain: 'play', slug: '6-9-play',
    title: '探索遊びの本格化', evidence: 'B', typical_range: '—',
    emerges: ['何でも触る・振る・落とす・口で確かめる', '玩具より日用品への興味'],
    high_leverage: ['安全な日用品の「宝箱」（木のスプーン・布・容器）', '床の探索圏を広げる'],
    father_edge: '「ダメ」を減らすのは環境設計で。触ってよい物だけの空間を作れば、探索を止めずに済む。',
    red_flags: [], related: ['/domains/play/', '/activities/floor-freedom/'], updated: '2026-07-06',
  },
  {
    ageBand: '6-9', domain: 'literacy', slug: '6-9-literacy',
    title: '絵と指さしの入り口', evidence: 'B', typical_range: '—',
    emerges: ['絵への注視が長くなる', 'ページをめくろうとする', '読み手の指さしを目で追う'],
    high_leverage: ['絵を指さして名づけながら読む', '子のペースでめくらせる（順番どおりでなくてよい）'],
    father_edge: '「読み終える」ことを目標にしない。1ページで脱線しても、それが正しい読み方。',
    red_flags: [], related: ['/activities/dialogic-reading/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 9-12ヶ月（+5） ================
  {
    ageBand: '9-12', domain: 'math-spatial', slug: '9-12-math',
    title: '入れる・出す・はめる', evidence: 'C', typical_range: '—',
    emerges: ['容器への出し入れの反復', '大小の関係の実験（入る/入らない）', '積もうとする'],
    high_leverage: ['入れ子カップ・箱と小物', '「入った！」「大きいね」の声かけ'],
    father_edge: '「入らないねえ、どうする？」と実況して試行錯誤を見守る。答えは先に言わない。',
    red_flags: [], related: ['/activities/container-play/', '/activities/stacking-nesting/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'music', slug: '9-12-music',
    title: '音楽で体が動く', evidence: 'B', typical_range: '—',
    emerges: ['音楽に合わせて体を揺らす', '手遊び歌の動きをまねしようとする', '好きな歌で機嫌が変わる'],
    high_leverage: ['手遊び歌のレパートリーを2〜3曲', '「うたの続き待ち」で発声を促す'],
    father_edge: '踊る父ほど強い教材はない。恥は家の外に置いてくる。',
    red_flags: [], related: ['/activities/song-pause/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'sensory', slug: '9-12-sensory',
    title: '感触の好みと実験', evidence: 'B', typical_range: '—',
    emerges: ['素材による触り方の変化', '食材の感触遊び（ぐちゃぐちゃ）', '冷たい/温かいへの反応'],
    high_leverage: ['安全な素材の感触遊び', '手づかみ食べの許容（散らかりは学習コスト）'],
    father_edge: '「汚れるからダメ」を言わない係。片付けごと引き受けて、感触の実験を保証する。',
    red_flags: ['特定の感触への極端な拒否が広範囲に及び生活に支障'], related: ['/activities/sensory-bin/', '/domains/sensory/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'play', slug: '9-12-play',
    title: 'やりとり遊びの成立', evidence: 'B', typical_range: '—',
    emerges: ['「どうぞ/ちょうだい」の往復', 'まねっこ遊び', '大人を遊びに誘う'],
    high_leverage: ['物の受け渡し遊び', '子の動きをまね返す'],
    father_edge: '子から遊びに誘われたら最優先で応じる。「誘えば来る」という確信が社会性の元手。',
    red_flags: ['やりとり遊び（どうぞ・ばあ等）への関心が全く見られない'], related: ['/activities/copycat-game/', '/domains/play/'], updated: '2026-07-06',
  },
  {
    ageBand: '9-12', domain: 'literacy', slug: '9-12-literacy',
    title: 'お気に入りの1冊の誕生', evidence: 'B', typical_range: '—',
    emerges: ['特定の本を繰り返し要求', '絵の指さし', '擬音への笑い'],
    high_leverage: ['同じ本の反復に付き合う', '擬音を大げさに読む'],
    father_edge: '100回目の「もう一回」にも初回のように付き合う——反復は語彙の定着作業。',
    red_flags: [], related: ['/activities/onomatopoeia-play/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 12-18ヶ月（+4） ================
  {
    ageBand: '12-18', domain: 'math-spatial', slug: '12-18-math',
    title: '大小・形の実地実験', evidence: 'C', typical_range: '—',
    emerges: ['大きい物に小さい物を入れる方向性の理解', '簡単な型はめ', '「もういっこ」の要求'],
    high_leverage: ['型はめパズル・入れ子', '「もういっこ？ はい、どうぞ」で数の言葉を'],
    father_edge: '「どっちが大きい？」と2択で聞いて選ばせる。正誤は問わず、比べる行為を面白がる。',
    red_flags: [], related: ['/activities/stacking-nesting/', '/domains/math-spatial/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'music', slug: '12-18-music',
    title: '拍とダンスの芽', evidence: 'B', typical_range: '—',
    emerges: ['音楽で自発的に踊る', '楽器（マラカス等）を鳴らして楽しむ', '好きな曲の要求'],
    high_leverage: ['ダンスタイムを日課に', '手づくりマラカスで合奏'],
    father_edge: '「パパの曲」を1曲決めて毎回同じダンスを。定番化が参加を生む。',
    red_flags: [], related: ['/activities/homemade-shakers/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'sensory', slug: '12-18-sensory',
    title: '全身で感じる屋外', evidence: 'B', typical_range: '—',
    emerges: ['歩行による探索圏の拡大', '砂・水・葉など自然素材への没頭', '天候の体感（風・雨・寒暖）'],
    high_leverage: ['毎日の外遊び', 'はだし・水たまり・砂場の解禁'],
    father_edge: '汚れる遊びの引率は父の職務。着替えを持てば、雨の日も教材になる。',
    red_flags: [], related: ['/activities/barefoot-textures/', '/science/13-nature-outdoors/'], updated: '2026-07-06',
  },
  {
    ageBand: '12-18', domain: 'literacy', slug: '12-18-literacy',
    title: '指さし読みと単語の収穫', evidence: 'B', typical_range: '—',
    emerges: ['絵本の絵を指さして名前を求める', '知っている物の絵に反応', '本を持ってくる'],
    high_leverage: ['指さしに全部応じて名づける', '「〇〇はどこ？」の探し読み'],
    father_edge: '本を持ってきたら原則断らない。「持ってくれば読んでもらえる」が読書習慣の種。',
    red_flags: [], related: ['/activities/point-and-respond/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 18-24ヶ月（+4） ================
  {
    ageBand: '18-24', domain: 'math-spatial', slug: '18-24-math',
    title: '2つの世界 — 「いっこ」と「いっぱい」', evidence: 'C', typical_range: '—',
    emerges: ['「ひとつ」の理解の芽', '多い/少ないの比較', '形の区別（丸・四角）の入り口'],
    high_leverage: ['「ひとつどうぞ」の実践', 'おやつ・積み木で多い少ないを体感'],
    father_edge: '数唱を教え込むより「ひとつ取って」が通じる喜びを。数は生活の道具として。',
    red_flags: [], related: ['/activities/count-everyday/', '/domains/math-spatial/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'music', slug: '18-24-music',
    title: '歌の一部を歌う', evidence: 'B', typical_range: '—',
    emerges: ['知っている歌の語尾・サビを歌う', 'リズムの模倣（トントン→トントン）', '強弱の面白さ'],
    high_leverage: ['うたの続き待ち', 'リズムのまねっこ・おおきい音ちいさい音'],
    father_edge: 'わざと歌詞を間違えて「ちがう！」と直させる遊びは、この時期から効く。',
    red_flags: [], related: ['/activities/loud-soft-game/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'sensory', slug: '18-24-sensory',
    title: '感覚のことば化が始まる', evidence: 'B', typical_range: '—',
    emerges: ['「つめたい」「いたい」など感覚語の理解', '感触の好み・苦手の主張', '五感の遊びへの没頭時間の延び'],
    high_leverage: ['感覚語を添える習慣（ざらざら・ふわふわ）', '感触カード・粘土・水遊び'],
    father_edge: '「どんな感じ？」と問い、子の言葉を待つ。感覚を言葉にできる子は自分の状態も語れるようになる。',
    red_flags: [], related: ['/activities/texture-book-diy/', '/domains/sensory/'], updated: '2026-07-06',
  },
  {
    ageBand: '18-24', domain: 'literacy', slug: '18-24-literacy',
    title: '物語の入り口 — 筋を追い始める', evidence: 'B', typical_range: '—',
    emerges: ['短い筋のある絵本を通しで聞ける', 'セリフの唱和（「うんとこしょ」）', '本の中の出来事への感情反応'],
    high_leverage: ['対話的読み聞かせ（問いを混ぜる）', '繰り返し構造の絵本'],
    father_edge: '「次はどうなる？」の一言を足すだけで、聞く読書が考える読書になる。',
    red_flags: [], related: ['/activities/dialogic-reading/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 24-30ヶ月（+4） ================
  {
    ageBand: '24-30', domain: 'fine-motor', slug: '24-30-fine-motor',
    title: 'ぐるぐる描きと道具の上達', evidence: 'B', typical_range: '—',
    emerges: ['ぐるぐる円のなぐり書き', 'スプーン・フォークの安定', 'ねじる動作（ふた開け）の芽'],
    high_leverage: ['毎日描ける環境（紙とクレヨンを出しっぱなしに）', 'ふた付き容器・ねじのおもちゃ'],
    father_edge: 'ペットボトルのふた開け係を任命。「ねじる」は生活の中で一番練習できる。',
    red_flags: [], related: ['/activities/window-drawing/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'music', slug: '24-30-music',
    title: '歌って踊れる — 表現の始まり', evidence: 'B', typical_range: '—',
    emerges: ['1曲を通して歌おうとする', '振り付きの歌の再現', '即興の歌（自作ソング）'],
    high_leverage: ['子の自作ソングに伴奏（手拍子）をつける', 'ダンス＆ストップで緩急'],
    father_edge: '子が歌い出したら止めない・直さない。即興の歌は言語と創造の交差点。',
    red_flags: [], related: ['/activities/dance-freeze/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'sensory', slug: '24-30-sensory',
    title: '感覚を使い分ける', evidence: 'C', typical_range: '—',
    emerges: ['見ないで触って当てる遊びができ始める', '音だけで物を当てる', '匂い・味の言葉の芽'],
    high_leverage: ['袋の中身を手探りで当てる遊び', 'おとさがし（耳をすます）'],
    father_edge: '「目をつぶってごらん」——1つの感覚を切って遊ぶと、他の感覚が主役になる。',
    red_flags: [], related: ['/activities/sound-hunt/', '/domains/sensory/'], updated: '2026-07-06',
  },
  {
    ageBand: '24-30', domain: 'literacy', slug: '24-30-literacy',
    title: '「よんで」の連続と暗唱', evidence: 'B', typical_range: '—',
    emerges: ['お気に入りの本の暗唱（覚えて"読む"ふり）', '長めの物語を聞ける', '文字への漠然とした興味'],
    high_leverage: ['暗唱の"読み聞かせごっこ"に観客として付き合う', '図書館の日で本の幅を広げる'],
    father_edge: '子が「読んでくれる」ときは最高の観客になる。読む側の経験が本好きを固める。',
    red_flags: [], related: ['/activities/library-habit/', '/domains/literacy/'], updated: '2026-07-06',
  },
  // ================ 30-36ヶ月（+3） ================
  {
    ageBand: '30-36', domain: 'music', slug: '30-36-music',
    title: 'リズムの正確さと歌の世界', evidence: 'B', typical_range: '—',
    emerges: ['拍に合わせる正確さの向上', 'レパートリーの拡大', '「かなしい曲/たのしい曲」の感受'],
    high_leverage: ['コール＆レスポンス・合奏ごっこ', '曲の気分を言葉にする（「この曲どんな気持ち？」）'],
    father_edge: '父のプレイリストを一緒に聴いて感想を言い合う。音楽の好みの世界を広げるのは父の音楽体験。',
    red_flags: [], related: ['/activities/call-response-song/', '/domains/music/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'sensory', slug: '30-36-sensory',
    title: '観察の解像度が上がる', evidence: 'C', typical_range: '—',
    emerges: ['細部への気づき（虫の脚・葉の筋）', '季節・天気の変化への言及', '感覚の記憶（「この前の海とおなじ匂い」）'],
    high_leverage: ['虫めがね・観察さんぽ', '季節の定点観察（同じ木を見に行く）'],
    father_edge: '「ほんとだ、よく見つけたね」——子の発見に驚ける父が、観察する子を育てる。',
    red_flags: [], related: ['/activities/nature-collecting/', '/science/13-nature-outdoors/'], updated: '2026-07-06',
  },
  {
    ageBand: '30-36', domain: 'literacy', slug: '30-36-literacy',
    title: '物語る側へ — お話づくりと文字の芽', evidence: 'B', typical_range: '—',
    emerges: ['自分でお話を作る', '経験を順序立てて話す芽', '自分の名前の文字への興味'],
    high_leverage: ['絵本でお話づくり・寝る前の「今日いちばん」', '名前の文字を遊びで見せる（教え込まない）'],
    father_edge: '「それでどうなったの？」と続きを促す聞き手役。物語る力は聞いてくれる人がいて育つ。',
    red_flags: ['ことばのやりとり・簡単な会話が成立しにくい状態が続く'], related: ['/activities/wordless-storytelling/', '/activities/bedtime-recap/'], updated: '2026-07-06',
  },
];
