// 粗大運動・微細運動・感覚系の活動カード
export default [
  {
    slug: 'obstacle-crawl', title: 'クッション障害物コース', type: 'activity',
    summary: 'クッションや布団で山や坂を作り、登る・越える・降りるを促す。全身の協応とバランス、挑戦心を育てる。',
    domains: ['gross-motor', 'play'], ageRange: { minMonths: 9, maxMonths: 30 },
    minutes: 15, effort: 'medium', materials: ['クッション', '布団', '大きな箱'], goals: ['スポーツに効く'], evidence: 'C',
    father_edge: '父が"山"や"トンネル"になって一緒に体を張れる。難度を子に合わせて即興で調整。',
    steps: ['クッション等で低い山・坂・トンネルを作る', '安全を確認し、子に自由に挑戦させる', '手を出しすぎず、必要な時だけ支える', '越えられたら一緒に喜ぶ'],
    why: '登る・越える・降りるは、バランス（前庭）・力加減（固有感覚）・運動計画を統合する。適度な挑戦が身体の自信を育てる。',
    variations: ['ゴールに玩具を置く', '「よーいドン」で止まる要素を足しEFも刺激'],
    safety: '硬い角・落下先を除き、必ず見守る。無理な高さにしない。',
    related: ['/domains/gross-motor/', '/science/09-movement/'], updated: '2026-07-06',
  },
  {
    slug: 'ball-roll-catch', title: 'ボール転がし・受け渡し', type: 'activity',
    summary: '向かい合ってボールを転がし合う。目と手の協応、順番、予測、やりとりの往復を育てる。',
    domains: ['gross-motor', 'fine-motor', 'social-emotional'], ageRange: { minMonths: 9, maxMonths: 36 },
    minutes: 10, effort: 'low', materials: ['やわらかいボール'], goals: ['スポーツに効く'], evidence: 'C',
    father_edge: '距離やスピードを子の力量に合わせて調整。将来の投球・捕球の土台づくり。',
    steps: ['向かい合って座る', 'ゆっくりボールを転がす', '子が返すのを待ち、返ってきたら喜ぶ', '慣れたら距離や速さを少し変える'],
    why: '転がる物の軌道を予測して手を出す経験が、視覚と運動の協応（後の捕球・道具操作の土台）を育てる。順番の往復は社会性も。',
    variations: ['月齢が上がったら投げる・蹴るへ', '大小のボールで感覚を変える'],
    safety: '硬いボールや小さすぎるボールは避ける。',
    related: ['/domains/gross-motor/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    slug: 'stacking-nesting', title: '積む・入れ子', type: 'activity',
    summary: 'ブロックを積む、カップを入れ子にする。微細運動・空間認知・大小の理解・因果を同時に育てる定番。',
    domains: ['fine-motor', 'math-spatial'], ageRange: { minMonths: 9, maxMonths: 30 },
    minutes: 10, effort: 'low', materials: ['積み木', '大小のカップ'], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '崩す楽しさも大事。積んで崩して、を一緒に面白がる。',
    steps: ['積み木やカップを渡す', '積む・重ねる・入れるのを見守る', '「大きい」「小さい」「上」「入った」と言葉を添える', '崩れても失敗と扱わず一緒に笑う'],
    why: '積む・入れ子は、手指の制御に加え、大小・空間・バランス・因果の直感を育てる。空間認知は後の数学と関連する。',
    variations: ['色や大きさで並べる（分類・系列）', '高く積む挑戦'],
    safety: '誤飲サイズの部品は避ける。',
    related: ['/domains/math-spatial/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    slug: 'sensory-bin', title: '感触あそび（水・砂・粘土）', type: 'activity',
    summary: '水・砂・粘土などに触れて探索する。多感覚・微細運動・語彙（つるつる等）・集中を育てる。',
    domains: ['sensory', 'fine-motor', 'language'], ageRange: { minMonths: 12, maxMonths: 36 },
    minutes: 15, effort: 'medium', materials: ['水/砂/粘土など', '容器', 'タオル'], goals: ['創造性', '勉強に効く'], evidence: 'C',
    father_edge: '散らかしを許せるかがカギ。屋外や風呂場でダイナミックにやれるのは父の強み。',
    steps: ['安全な素材を容器に用意', '自由に触る・すくう・こねるを見守る', '感触を言葉にする（「ざらざら」「つめたい」「やわらかい」）', '片付けまで一緒に'],
    why: '多感覚の探索は知覚を精緻にし、微細運動と感覚のことば化を促す。没頭は集中力の練習にもなる。',
    variations: ['道具（スプーン・型）を足す', '色水で色の学び'],
    safety: '口に入れる時期は素材に注意。水遊びは絶対に目を離さない。',
    related: ['/domains/sensory/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    slug: 'dance-freeze', title: 'ダンス＆ストップ', type: 'activity',
    summary: '音楽で踊り、止まったらピタッと止まる。リズム・全身運動に加え、抑制制御（実行機能）を楽しく鍛える。',
    domains: ['gross-motor', 'music', 'executive-function'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 10, effort: 'medium', materials: ['音楽'], goals: ['スポーツに効く', '勉強に効く'], evidence: 'B',
    father_edge: '父が全力で踊り、全力で固まる。おおげさなモデルが子の抑制を引き出す。',
    steps: ['音楽をかけて一緒に自由に踊る', '音を止めたら「ストップ！」でピタッと止まる', 'また音楽で動く、を繰り返す', '慣れたら「ゆっくり/速く」も足す'],
    why: '「動く」を「止める」に切り替える遊びは、衝動を抑える抑制制御（実行機能の中核）を楽しく鍛える。リズムと全身運動も同時に。',
    variations: ['特定の音で特定のポーズ（ルール切替＝認知的柔軟性）', 'スロー再生で難度アップ'],
    safety: '滑らない床で、ぶつかる物を除く。',
    related: ['/domains/executive-function/', '/domains/music/'], updated: '2026-07-06',
  },
];
