// 実行機能・自己制御（抑制・切り替え・ワーキングメモリ）の活動カード（薄いドメインの補強・P2-図鑑B）。
// 「訓練で頭を良くする」ではなく、遊びの中で抑制・切り替え・記憶を楽しく使う場を作る。時期は目安。
export default [
  {
    slug: 'opposite-game', title: 'はんたいゲーム（言われた逆をやる）', type: 'activity',
    summary: '「大きく」と言われたら小さく、逆の動きをする遊び。反射的な反応を止めてルールで動く、抑制と切り替えの練習。',
    domains: ['executive-function', 'gross-motor', 'language'], ageRange: { minMonths: 30, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '父がわざと引っかかってみせると子は大喜び。間違いを笑い合える空気が挑戦を後押しする。',
    steps: ['「大きくなって」で小さく、を最初に見せる', '簡単な1組の反対から始める（大きい↔小さい）', '慣れたら「はやい↔ゆっくり」など組を増やす', '間違えても責めず、笑って続ける'],
    why: '言われた通りに反応したくなる衝動を抑え、ルールに沿って別の反応を選ぶ課題は、抑制制御と切り替え（実行機能の中核）を使う。楽しい遊びの形にすることで、失敗を恐れず繰り返し練習できる。ただし個々の遊びが将来の学力を高めるという強い証拠はない。',
    variations: ['声の大小の反対版', '絵カードで「これじゃない方」を指す'],
    safety: null, related: ['/domains/executive-function/', '/activities/copycat-game/'], updated: '2026-07-06',
  },
  {
    slug: 'traffic-light-game', title: 'あか・あお・きいろ（信号ゲーム）', type: 'activity',
    summary: '「あお」で進み「あか」で止まる。色の合図で動きを制御する遊び。合図を替えると切り替えの練習にもなる。',
    domains: ['executive-function', 'gross-motor'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '信号役の父が緩急をつけて出題。急に「あか！」で止められるかのスリルを演出できる。',
    steps: ['「あおは進む、あかは止まる」を決めて歩く/走る', '父が「あお」「あか」と合図を出す', '「きいろはゆっくり」を足して段階を上げる', '慣れたら合図の意味を入れ替える（切り替え課題）'],
    why: '合図に応じて動きを始める・止めることは抑制制御を使い、「あかで止まる」に成功するには衝動を抑える必要がある。合図の意味を途中で入れ替えると、覚えたルールを更新する切り替えの練習になる。信号のルールを生活で学ぶ実用性もある。',
    variations: ['音（太鼓）で進む・止まる', '手を挙げる／下げるを合図に'],
    safety: '走る場合は転倒・衝突に注意し、広く安全な場所で。道路の実際の信号とは分けて教える。',
    related: ['/domains/executive-function/', '/activities/dance-freeze/'], updated: '2026-07-06',
  },
  {
    slug: 'memory-tray', title: 'なくなったの なあに（記憶トレイ）', type: 'activity',
    summary: 'いくつかの物を見せてから1つ隠し、「何がなくなった？」と当てる。見たものを覚えておくワーキングメモリの遊び。',
    domains: ['executive-function', 'language', 'play'], ageRange: { minMonths: 30, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: ['身近な小物2〜4個', '布・箱'], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '隠す手品のような演出が父の腕の見せどころ。「よーく見てて…」の間で注意を集める。',
    steps: ['小物を2〜3個並べて名前を確認する', '「よく見てね」と少し眺めさせる', '布で隠して1つこっそり抜く', '「なにがなくなった？」と当てさせる（数は徐々に増やす）'],
    why: '並んだ物を記憶に保持し、消えた物と照合して答える課題は、ワーキングメモリと注意を使う。物の数を増やすことで難度を調整でき、成功体験を積みながら記憶の負荷を少しずつ上げられる。',
    variations: ['位置を入れ替える版（何が動いた？）', '2個増やして難度アップ'],
    safety: '誤飲サイズの小物は使わない。', related: ['/domains/executive-function/', '/activities/hide-and-seek-objects/'], updated: '2026-07-06',
  },
  {
    slug: 'sorting-switch', title: 'わけかたチェンジ（基準の切り替え）', type: 'activity',
    summary: '積み木を「色で分けた」後に「今度は形で」と基準を変えて分け直す。ルールを切り替える認知的柔軟性の遊び。',
    domains: ['executive-function', 'math-spatial', 'fine-motor'], ageRange: { minMonths: 30, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: ['色と形が違う積み木やブロック'], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '「次はこっちのルールね」と切り替えを楽しく仕切る進行役に。急がず前のルールを手放す時間を待つ。',
    steps: ['まず色で分ける（赤の山・青の山）', 'できたら「今度は形で分けよう」と基準を変える', '前のルールに引きずられても責めない', '「大きさで」など基準をもう一つ増やす'],
    why: 'いったん覚えた分類ルールを手放し、新しいルールで分け直すことは、切り替え（認知的柔軟性）という実行機能を使う。2〜3歳では前のルールに引きずられやすく、これを少しずつ乗り越える経験が柔軟性を育てると考えられている。',
    variations: ['洗濯物・おもちゃの片付けで基準替え', '「大きい/小さい」→「色」へ'],
    safety: null, related: ['/domains/executive-function/', '/activities/sorting-game/'], updated: '2026-07-06',
  },
  {
    slug: 'first-then-plan', title: '「これしたら、つぎ」（見通しと待つ力）', type: 'activity',
    summary: '「靴はいたら、公園ね」と順番を言葉と絵で示す。次の楽しみのために今を進める、計画と我慢の芽を育てる。',
    domains: ['executive-function', 'language', 'social-emotional'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 2, effort: 'low', materials: [], goals: ['勉強に効く', '情緒'], evidence: 'C',
    father_edge: '見通しを言葉で示すのは父も担える。約束を必ず守ることで「待てば来る」という信頼を積む。',
    steps: ['「〇〇したら、つぎは〇〇」と2ステップで伝える', '絵や指で順番を見せると分かりやすい', '約束した「つぎ」は必ず実行する', 'できたら「待てたね」と過程を認める'],
    why: '「今これ→次あれ」の見通しは、目の前の欲求を少し抑えて順序立てて行動する練習になる。約束が守られる経験は、待つことへの信頼（満足の遅延の土台）を育てる。罰でなく見通しで動機づけるのがポイント。',
    variations: ['お支度ボード（絵で順番）', '「あと1回で交代ね」の予告'],
    safety: null, related: ['/domains/executive-function/', '/activities/waiting-games/'], updated: '2026-07-06',
  },
  {
    slug: 'puzzle-persistence', title: 'パズルで「もうちょっと」', type: 'activity',
    summary: '少しだけ難しいパズルに、投げ出さず取り組む。うまくいかない気持ちに付き合い、やり抜く力の芽を育てる。',
    domains: ['executive-function', 'fine-motor', 'math-spatial'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 10, effort: 'low', materials: ['型はめ・ピースの少ないパズル'], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '答えを教えず「ここを回してみたら？」と最小限のヒントで支える足場かけは父の腕の見せどころ。',
    steps: ['子の力より少しだけ難しいパズルを選ぶ', 'すぐ手を出さず、まず自分で試させる', '詰まったら答えでなくヒントを一つだけ出す', 'できたら「あきらめなかったね」と過程をほめる'],
    why: 'できそうでできない課題に留まる経験は、いらだちを抱えながら注意を維持する自己制御を使う。大人が答えでなくヒントで支える（足場かけ）と、子は自力で解けたと感じ、やり抜く姿勢と有能感が育つ。',
    variations: ['ピース数を段階的に増やす', '完成したら一緒に崩してまた挑戦'],
    safety: '誤飲サイズの小ピースは避ける。', related: ['/domains/executive-function/', '/activities/stacking-nesting/'], updated: '2026-07-06',
  },
  {
    slug: 'quiet-loud-voice', title: 'こえの大きさコントロール', type: 'activity',
    summary: '「大きな声」「ないしょ声」を場面で使い分ける遊び。声の大きさを自分で調整する、身近な自己制御の練習。',
    domains: ['executive-function', 'language', 'social-emotional'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 3, effort: 'low', materials: [], goals: ['勉強に効く', '情緒'], evidence: 'C',
    father_edge: '低い声で「ないしょ声…」とやると子は夢中に。父の声色の幅が遊びを豊かにする。',
    steps: ['「大きな声で名前を言って！」', '「今度はないしょ声で…」とささやく', '場面と結ぶ（外は大きく、寝る前は小さく）', 'ゲームとして楽しみ、静かにできたら認める'],
    why: '声の大きさを合図に合わせて調整することは、衝動的な発声を抑えて意図的に制御する抑制の練習になる。「今は静かに」を場面で選べることは、社会的な自己制御の入り口でもある。',
    variations: ['ロボット声・ぞうさん声など声色ごっこ', '「しーっ」ゲームで一番静かに'],
    safety: null, related: ['/domains/executive-function/', '/activities/emotion-labeling/'], updated: '2026-07-06',
  },
  {
    slug: 'turn-taking-game', title: '順番こ（かわりばんこ）', type: 'activity',
    summary: '積み木を交代で積む、ボールを転がし合うなど「じゅんばん」を守る遊び。待って・自分の番で動く自己制御。',
    domains: ['executive-function', 'social-emotional', 'play'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: ['積み木・ボールなど'], goals: ['勉強に効く', '情緒'], evidence: 'C',
    father_edge: '「パパの番、〇〇ちゃんの番」とテンポよく回す進行役。父が自分の番を待つ手本を見せられる。',
    steps: ['「かわりばんこね」と交代のルールを決める', '「パパの番」「〇〇ちゃんの番」と声に出す', '相手の番は手を出さずに待つ', '待てたことを「順番まてたね」と認める'],
    why: '自分の番まで待ち、番が来たら動くには、行動したい衝動を抑えるタイミングの制御が要る。交代の経験は自己制御に加え、相手の存在を意識する社会性（協調）の土台にもなる。',
    variations: ['簡単なすごろく風', '絵本を交代でめくる'],
    safety: null, related: ['/domains/executive-function/', '/activities/ball-roll-catch/'], updated: '2026-07-06',
  },
  {
    slug: 'slow-motion-game', title: 'スローモーションあそび', type: 'activity',
    summary: '「そーっと、ゆーっくり」歩く・動く遊び。速く動きたい衝動を抑えて、わざとゆっくり動く運動の自己制御。',
    domains: ['executive-function', 'gross-motor'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 3, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '大きな体でスローモーションを大げさに演じると子は大笑い。父の全身芝居が引き込む。',
    steps: ['「スローモーションで歩こう」とゆっくり動いて見せる', '子と一緒に超スローで進む', '「そーっとコップを運ぶ」など生活に応用', '速い→遅いの切り替えを混ぜる'],
    why: '速く動きたい自然な衝動を抑えて意図的にゆっくり動くことは、運動の抑制制御を使う。「そーっと運ぶ」など生活場面に応用でき、力と速さを状況に合わせて調整する練習になる。',
    variations: ['だるまさんがころんだの前段', '「音を立てずに」忍者ごっこ'],
    safety: null, related: ['/domains/executive-function/', '/activities/dance-freeze/'], updated: '2026-07-06',
  },
];
