// 音楽・リズム・聴覚の活動カード（薄いドメインの補強・P2-図鑑A）。
// 「才能開発」ではなく、拍・音色・声を通じた聴覚と情動・運動の統合を土台にする。時期は目安。
export default [
  {
    slug: 'steady-beat-bounce', title: 'ひざでビート（拍にのる）', type: 'activity',
    summary: '子を膝にのせ、歌や音楽の拍に合わせて上下にゆらす。一定の拍を体で感じる経験は、リズム感と聴覚の土台。',
    domains: ['music', 'gross-motor', 'social-emotional'], ageRange: { minMonths: 0, maxMonths: 24 },
    minutes: 3, effort: 'low', materials: [], goals: ['情緒'], evidence: 'C',
    father_edge: '抱っこ・膝のせは父の得意分野。しっかり支えて安定した拍を刻める。',
    steps: ['子を膝や胸に抱き、安定して支える', '歌いながら拍に合わせて優しく上下にゆらす', 'テンポを一定に保つ（速すぎない）', '子が声や体で応じたら、それに合わせて続ける'],
    why: '一定の拍に体で同期する経験は、聴覚と運動の統合や拍の知覚の基礎になると考えられている。抱かれてゆれる心地よさは情動の同調も生む。乳児期からの拍の経験と後の音楽・言語の関連は研究途上で、断定はできない。',
    variations: ['音楽をかけて抱っこでゆっくり踊る', '座れる子は向かい合って手を持ってゆらす'],
    safety: '首すわり前は頭をしっかり支える。揺さぶりすぎない（激しい上下運動は避ける）。',
    related: ['/domains/music/', '/activities/singing-daily/'], updated: '2026-07-06',
  },
  {
    slug: 'lullaby-dad-voice', title: '子守唄（父の低い声で）', type: 'activity',
    summary: '同じ子守唄を毎日そっと歌う。父の低い声は母と違う音色で、歌でつながる時間そのものが情緒と聴覚を育てる。',
    domains: ['music', 'social-emotional', 'language'], ageRange: { minMonths: 0, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['情緒'], evidence: 'C',
    father_edge: '父の低く響く声は、母の声とは違う音域・音色の入力になる。上手下手は関係ない。',
    steps: ['決まった子守唄を1〜2曲もつ', '静かな場面でゆっくり、小さめの声で歌う', '毎日同じ歌を繰り返す（安心の合図になる）', '子の様子を見ながら、応じる声には応える'],
    why: '歌は言葉より音程・リズムが誇張され、乳児の注意と情動に働きかけやすい。決まった歌の繰り返しは予測できる安心の合図になり、養育者との情動的なつながりを深める。父の低い声は聴覚入力の多様性を増やす。（寝かしつけの手技ではなく、歌でつながる時間として。）',
    variations: ['抱っこでゆらしながら', '日中の落ち着かせたい時間にも'],
    safety: null, related: ['/domains/music/', '/science/04-attachment/'], updated: '2026-07-06',
  },
  {
    slug: 'body-percussion', title: 'からだで音（手拍子・足踏み）', type: 'activity',
    summary: '手拍子・膝たたき・足踏みで簡単なリズムを作り、子に真似させる。道具なしでできるリズム模倣あそび。',
    domains: ['music', 'gross-motor', 'executive-function'], ageRange: { minMonths: 12, maxMonths: 36 },
    minutes: 3, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '大きな動作でダイナミックにやれるのが父の強み。全身を使ったリズム遊びに発展させやすい。',
    steps: ['「パン・パン」と簡単な手拍子をする', '子に「まねっこして」と促す', '足踏み・膝たたきなど音の種類を増やす', '子が作ったリズムを父が真似し返す（役割交代）'],
    why: 'リズムの模倣は、聴いた音のパターンを記憶して運動で再現する課題で、聴覚と運動の協応・注意・模倣を同時に使う。役割交代はやりとりの構造（ターンテイキング）の練習にもなる。',
    variations: ['歌に合わせて手拍子', '「はやい・おそい」を混ぜる'],
    safety: null, related: ['/domains/music/', '/activities/rhythm-tapping/'], updated: '2026-07-06',
  },
  {
    slug: 'tempo-fast-slow', title: 'はやい・おそいごっこ（テンポ遊び）', type: 'activity',
    summary: '同じ歌を「はやく」「ゆっくり」歌い分けて動く。テンポの違いを聴き分け、体の動きで制御する遊び。',
    domains: ['music', 'gross-motor', 'executive-function'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '緩急のメリハリを大げさに演じられる父向き。動と静の切り替えを遊びにできる。',
    steps: ['知っている歌をふつうに歌って動く', '「はやくいくよ！」と速く歌い、速く動く', '「こんどはゆっくり…」と遅くする', '子に「はやい？おそい？」と選ばせて主導させる'],
    why: 'テンポの聴き分けと、それに動きを合わせる調整は、聴覚の弁別と運動の制御を結びつける。速さの急な切り替えに合わせて動きを止める・変えることは、抑制と切り替え（実行機能）の練習にもなる。',
    variations: ['大きい音・小さい音バージョン', '行進→スローモーション'],
    safety: null, related: ['/domains/music/', '/activities/dance-freeze/'], updated: '2026-07-06',
  },
  {
    slug: 'pots-and-pans-band', title: 'なべ・ボウルでドラム', type: 'activity',
    summary: '鍋・ボウル・空き容器を叩いて音の違いを楽しむ。素材で変わる音色と、強弱を自分で操る因果の実験。',
    domains: ['music', 'sensory', 'fine-motor'], ageRange: { minMonths: 8, maxMonths: 30 },
    minutes: 10, effort: 'medium', materials: ['鍋・ボウル・空き容器', '木べら・スプーン'], goals: ['創造性'], evidence: 'C',
    father_edge: '「音が大きい」ことを許せるのが父の役割。多少うるさくても実験として付き合える。',
    steps: ['安全な容器と叩く道具を用意する', '素材ごとに叩いて音の違いを聴く（金属・プラ・木）', '「大きい音」「小さい音」を叩き分ける', '歌に合わせてリズムを叩いて合奏する'],
    why: '自分の動きが音を生み、叩き方や素材で音が変わる体験は、聴覚の弁別と因果の理解を促す。強弱の叩き分けは力の調整（運動制御）の練習になる。散らかりと音を許容できる環境がカギ。',
    variations: ['水の量を変えたコップで音階（2歳〜）', '中身入り容器で音の違い'],
    safety: '割れ物・角のある物は避け、口に入るサイズの道具は使わない。耳元で強く鳴らさない。',
    related: ['/domains/music/', '/activities/homemade-shakers/'], updated: '2026-07-06',
  },
  {
    slug: 'scarf-dance', title: 'スカーフで音楽ダンス', type: 'activity',
    summary: '薄い布やスカーフを持って音楽に合わせて動く。音の流れを体と布の動きで表現する、全身の音楽あそび。',
    domains: ['music', 'gross-motor', 'sensory'], ageRange: { minMonths: 12, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: ['薄いスカーフ・布'], goals: ['創造性', '情緒'], evidence: 'C',
    father_edge: '照れずに一緒にひらひら踊れるか。父が全力で踊るほど子も解放される。',
    steps: ['軽い布を子と1枚ずつ持つ', '音楽に合わせて振る・回す・上下させる', '「ゆっくりな曲」「元気な曲」で動きを変える', '布を投げ上げて落ちるのをキャッチして遊ぶ'],
    why: '音楽に合わせて全身を動かす経験は、聴いた音を運動で表現する統合を促す。布という道具は動きを目に見える形にし、テンポや強弱の変化への反応を引き出す。表現の自由さは情緒の解放にもつながる。',
    variations: ['スカーフでいないいないばあ', '落ちる布を目で追ってキャッチ'],
    safety: '布を顔や首に巻きつけないよう見守る。走り回るときは周囲の安全を確保。',
    related: ['/domains/music/', '/activities/dance-freeze/'], updated: '2026-07-06',
  },
  {
    slug: 'transition-songs', title: '生活の歌（お片付け・おでかけソング）', type: 'activity',
    summary: '片付け・手洗い・出発などの場面に決まった歌をつける。歌が切り替えの合図になり、生活と音楽を結ぶ。',
    domains: ['music', 'executive-function', 'social-emotional'], ageRange: { minMonths: 12, maxMonths: 36 },
    minutes: 2, effort: 'low', materials: [], goals: ['勉強に効く', '情緒'], evidence: 'C',
    father_edge: '父の担当場面（お風呂・お出かけ準備）にオリジナルソングを作ると、切り替えがぐっと楽になる。',
    steps: ['場面ごとに決まった短い歌を決める（お片付けの歌など）', 'その場面のたびに毎回歌う', '歌の終わりまでに行動を終える遊びにする', '子が歌い出したら一緒に歌って行動する'],
    why: '決まった歌は次の行動の予告になり、見通しを与えて切り替えを助ける。「歌が終わるまでに」という枠は、時間の区切りと自己制御の練習にもなる。音楽が日常の移行をなめらかにする実用的な道具になる。',
    variations: ['数え歌で「10まで数える間に」', 'お気に入りの曲を出発の合図に'],
    safety: null, related: ['/domains/music/', '/domains/executive-function/'], updated: '2026-07-06',
  },
  {
    slug: 'high-low-sounds', title: 'たかい音・ひくい音あそび', type: 'activity',
    summary: '声や身近な音で「たかい／ひくい」を出し分けて遊ぶ。音の高さ（ピッチ）に注意を向ける聴覚の遊び。',
    domains: ['music', 'language', 'sensory'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 3, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: '低い声が出せる父は「ひくい音」担当がハマる。声色の幅で子を笑わせながら教えられる。',
    steps: ['「たかい声（ねずみ）」と「ひくい声（ぞう）」を出す', '子に真似させる', '動物や物に音の高さを結びつける（小鳥＝高い）', '「これはたかい？ひくい？」とクイズにする'],
    why: '音の高さへの注意（ピッチの弁別）は聴覚の重要な要素で、声色の遊びを通じて自然に育つ。高い・低いを言葉と結ぶことは、感覚経験を語彙に変換する練習にもなる。',
    variations: ['歌を高く・低く歌い分ける', 'コップの水量で音の高さ実験（2歳半〜）'],
    safety: null, related: ['/domains/music/', '/activities/sound-hunt/'], updated: '2026-07-06',
  },
  {
    slug: 'name-that-tune-hum', title: 'このうた なあに（くちずさみクイズ）', type: 'activity',
    summary: '歌詞なしで鼻歌のメロディだけ聞かせ、何の歌か当てる。旋律の記憶と聴き取りを使う、少し年上向けの遊び。',
    domains: ['music', 'language', 'executive-function'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 3, effort: 'low', materials: [], goals: ['勉強に効く'], evidence: 'C',
    father_edge: 'ハミングでもったいぶって出題する父の演技力が盛り上げるカギ。当たったら大げさに驚く。',
    steps: ['子がよく知る歌を歌詞なしで鼻歌にする', '「なんの歌でしょう？」と当てさせる', '当たったら一緒に歌詞つきで歌う', '子に出題役をやらせる（役割交代）'],
    why: '歌詞という手がかりなしに旋律だけから曲を同定するには、記憶の中の音のパターンと照合する必要があり、聴覚的記憶とパターン認識を使う。出題役への交代は、頭の中の旋律を保持して表現する練習になる。',
    variations: ['リズム（手拍子）だけで当てる', '出だしの1フレーズだけで当てる'],
    safety: null, related: ['/domains/music/', '/activities/song-pause/'], updated: '2026-07-06',
  },
];
