// P2e-図鑑: music を150到達に向けて補強（+6）
export default [
  {
    slug: 'body-percussion', title: 'からだパーカッション（手・ひざ・足）', type: 'activity',
    summary: '手拍子・ひざ打ち・足踏みを組み合わせて体で演奏。楽器いらずで、リズムと身体の協応を育てる。',
    domains: ['music', 'gross-motor', 'executive-function'], ageRange: { minMonths: 18, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['創造性', 'スポーツに効く'], evidence: 'C',
    father_edge: '「パン（手）・ポン（ひざ）・ドン（足）」を父が実演。だんだん組み合わせを増やして「ギリギリできる」難度を作る。',
    steps: ['手拍子「パン」から始めてまねさせる', 'ひざ打ち「ポン」、足踏み「ドン」を足す', '「パン・ポン」など2つの組み合わせに', '歌に合わせて体で伴奏する'],
    why: '体の各部位を打ち分けるボディパーカッションは、拍の知覚と身体の協調、複数動作の切り替え（実行機能）を同時に使う。楽器がなくてもどこでもでき、リズム感の土台を全身で育てられる。',
    variations: ['「パン・パン・ポン」の繰り返しパターン', '速さを変える'],
    safety: null, related: ['/activities/echo-clap/', '/activities/rhythm-tapping/', '/domains/music/'], updated: '2026-07-09',
  },
  {
    slug: 'hand-play-song', title: 'てあそびうた（むすんでひらいて）', type: 'activity',
    summary: '「むすんでひらいて」「げんこつやま」など手の動きつきの歌。歌・手指・記憶が一体になった伝承あそび。',
    domains: ['music', 'fine-motor', 'language'], ageRange: { minMonths: 6, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['創造性', '情緒'], evidence: 'B',
    father_edge: '自分が子どもの頃の手あそびを思い出せばレパートリー代ゼロ。膝に乗せて触れ合いながらできる。',
    steps: ['「むすんでひらいて」など手あそび歌を1つ選ぶ', 'ゆっくり手の動きを見せながら歌う', '子の手を取って一緒に動かす', '慣れたら速さを変えたり替え歌にする'],
    why: '歌詞・旋律・手の動きが結びついた手あそび歌は、音楽経験と微細運動、言葉の記憶を同時に育てる。動作の手がかりが歌詞の記憶を助け、繰り返しの中で拍やフレーズの感覚が身につく。',
    variations: ['「グーチョキパー」で形づくり', '動作を子に考えさせる'],
    safety: null, related: ['/activities/rhyme-time/', '/activities/singing-daily/', '/domains/music/'], updated: '2026-07-09',
  },
  {
    slug: 'name-song', title: 'なまえのうた（きみだけの即興ソング）', type: 'activity',
    summary: '「◯◯ちゃん、おはよう」と名前を旋律にのせて歌う。自分の名前が歌になる喜びは、音楽と自己を結ぶ。',
    domains: ['music', 'social-emotional', 'language'], ageRange: { minMonths: 0, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['情緒', '創造性'], evidence: 'C',
    father_edge: '朝の挨拶や着替えを「名前の歌」で始める父の習慣に。上手下手は無関係、名前を呼ぶ歌そのものが愛着を伝える。',
    steps: ['子の名前を簡単な節にのせて歌う（「◯◯ちゃん、おはよ〜」）', '場面ごとに歌詞を変える（ごはん・おふろ・おやすみ）', '子の反応（笑う・声を出す）を待って返す', '家族やぬいぐるみの名前バージョンに広げる'],
    why: '自分の名前を旋律にのせて聞く経験は、音楽的な快と自己の認識・愛着を結びつける。即興の歌は日常の移行（着替え・食事）の合図にもなり、予測可能性と安心を与える。',
    variations: ['行動を実況する即興ソング', '家族それぞれのテーマソング'],
    safety: null, related: ['/activities/lullaby-ritual/', '/activities/singing-daily/', '/domains/music/'], updated: '2026-07-09',
  },
  {
    slug: 'animal-sound-song', title: 'どうぶつの声で歌おう（ぞうさん・わんわん）', type: 'activity',
    summary: '知っている歌を「わんわん」「にゃーにゃー」だけで歌う。声色を変える遊びは、発声と音への注意を広げる。',
    domains: ['music', 'language'], ageRange: { minMonths: 12, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['創造性'], evidence: 'C',
    father_edge: '低い「がおー」から高い「ぴよぴよ」まで、声の芸で笑わせる父向き。声色の振り幅が遊びの幅になる。',
    steps: ['よく知る歌を選ぶ（きらきら星など）', '歌詞のかわりに「わんわん」だけで歌う', '「こんどはにゃーにゃーで」と声色を変える', '子に「なんの声で歌う？」と決めさせる'],
    why: '歌詞を動物の鳴き声に置き換えて歌う遊びは、旋律を保ちながら発声を変える練習になり、声のコントロールと音への注意を育てる。鳴き声の模倣は語彙・音韻の遊びにもつながる。',
    variations: ['乗り物の音（ブーブー）版', '高い声・低い声で歌い分け'],
    safety: null, related: ['/activities/onomatopoeia-play/', '/activities/voice-slide/', '/domains/music/'], updated: '2026-07-09',
  },
  {
    slug: 'clap-syllables', title: 'おなまえ手拍子（音の数だけパン）', type: 'activity',
    summary: '「り・ん・ご」で3回パン。言葉を音の粒に分けて叩く遊びは、音楽のリズムと読字の音韻意識の交差点。',
    domains: ['music', 'literacy'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['勉強に効く', '創造性'], evidence: 'B',
    father_edge: '家族の名前で「パパ＝パン・パン」と手拍子。生活の言葉を教材にする父のすきま遊び。',
    steps: ['子の名前を「◯・◯・◯」と区切って手拍子する', '「いくつ手を叩いたかな？」と数える', '身近な言葉（果物・家族）で叩き分ける', '長い言葉・短い言葉を比べる'],
    why: '単語を音節に分けて手拍子する遊びは、拍のリズム感と、言葉を音の単位に分解する力（音韻意識）を同時に育てる。音韻意識は読字の強力な予測因子で、リズム遊びとして自然に取り組める。',
    variations: ['足踏みバージョン', '長い言葉さがし競争'],
    safety: null, related: ['/activities/first-sound-game/', '/activities/echo-clap/', '/domains/literacy/'], updated: '2026-07-09',
  },
  {
    slug: 'high-low-conductor', title: 'しきしゃごっこ（高い声・低い声を操る）', type: 'activity',
    summary: '手を上げると高い声、下げると低い声。指揮者になって声をあやつる、音高と制御の遊び。',
    domains: ['music', 'executive-function'], ageRange: { minMonths: 24, maxMonths: 36 },
    minutes: 5, effort: 'low', materials: [], goals: ['創造性'], evidence: 'C',
    father_edge: '父が声を出し、子の手の高さに従う——主導権を子に渡すのがミソ。急な上げ下げで笑わせる。',
    steps: ['「手が上なら高い声、下なら低い声」とルールを決める', '子が手を上下し、父が声で従う', '役割交代して子が声を出す', '大きい/小さいも手で指揮する'],
    why: '手の高さと声の高さを対応させる遊びは、音高の知覚と発声のコントロールを結びつける。「合図に従って声を変える」課題は抑制と切り替え（実行機能）を使い、音楽表現を能動的に操る楽しさを教える。',
    variations: ['速い/遅いも指揮する', '楽器の音量を指揮'],
    safety: null, related: ['/activities/voice-slide/', '/activities/loud-soft-game/', '/domains/music/'], updated: '2026-07-09',
  },
];
