// 実践アクティビティカード（中核セット）。Opusはドメイン別ファイルで増築する。
export default [
  {
    slug: 'serve-return-narration', title: '実況中継トーク', type: 'activity',
    summary: '赤ちゃんの声・視線にすぐ応じ、見ているものを言葉にして返す。最強にして無料の言語＆愛着トレ。',
    domains: ['language', 'social-emotional', 'executive-function'],
    ageRange: { minMonths: 0, maxMonths: 36 }, minutes: 5, effort: 'low', materials: [],
    goals: ['勉強に効く', '情緒'], evidence: 'A',
    father_edge: '父ならではの語彙・話題（工具・乗り物・外の世界）が言語入力の幅を広げる。',
    steps: [
      '赤ちゃんが声を出す/何かを見たら、間を空けずに反応する',
      'その対象を短い言葉で実況する（「わんわん、いたね」）',
      '赤ちゃんの反応を待つ。返ってきたらまた返し、ラリーを続ける',
      '興味が切れたら追わない。次のサーブを待つ',
    ],
    why: '子の発信に速く関連した応答を返すと、「発信は世界を動かす」という予測が形成され、前頭前皮質を含む回路が強化される。語りかけ量は後の語彙・読解と関連する。',
    variations: ['月齢が上がったら子の言葉を"拡張"して返す（「ブーブー」→「赤いブーブー走ってるね」）', '入浴・着替えの時間に習慣化'],
    safety: null, related: ['/science/05-serve-return/'], updated: '2026-07-06',
  },
  {
    slug: 'tummy-time-play', title: 'うつ伏せ遊び（Tummy Time）', type: 'activity',
    summary: '首・体幹・肩の土台を作るうつ伏せ時間を、父の胸の上や玩具で"遊び"にする。',
    domains: ['gross-motor', 'sensory'], ageRange: { minMonths: 0, maxMonths: 6 },
    minutes: 5, effort: 'low', materials: ['丸めたタオル', 'カラフルな玩具や鏡'],
    goals: ['スポーツに効く'], evidence: 'B',
    father_edge: '父の胸の上に乗せる"胸うつ伏せ"は嫌がる子に有効。父の顔が最高の的になる。',
    steps: [
      '授乳直後を避け、機嫌のよい覚醒時に',
      '床（またはうつ伏せにした父の胸）にうつ伏せにする',
      '目の高さで声かけ・玩具・鏡で頭を上げる動機を作る',
      '最初は1〜2分から。1日数回、機嫌に合わせて少しずつ延ばす',
    ],
    why: 'うつ伏せは頸部・肩甲帯・体幹の抗重力筋を育て、寝返り〜はいはいの土台になる。後の姿勢制御・運動発達に寄与。',
    variations: ['月齢が上がったら手を伸ばす位置に玩具を置いてリーチを促す'],
    safety: '眠ってしまったら必ず仰向けに戻す（うつ伏せ寝は避ける）。目を離さない。',
    related: ['/domains/gross-motor/', '/roadmap/0-3/'], updated: '2026-07-06',
  },
  {
    slug: 'peekaboo', title: 'いないいないばあ', type: 'activity',
    summary: '対象の永続性とワーキングメモリの芽を育て、予測と驚きのやりとりで愛着も深める古典。',
    domains: ['executive-function', 'social-emotional', 'language'],
    ageRange: { minMonths: 3, maxMonths: 18 }, minutes: 3, effort: 'low', materials: [],
    goals: ['勉強に効く', '情緒'], evidence: 'B',
    father_edge: '大きな表情と声のダイナミクスは父が得意。驚きの"落差"を演出しやすい。',
    steps: ['顔や玩具を隠す', '「いないいない…」と少し"ため"を作る', '「ばあ！」で現す', '子の反応（笑い・声）を待ってまた繰り返す'],
    why: '隠れても存在し続けるという対象の永続性の理解を促し、"次に何が起こるか"を保持・予測する働き（ワーキングメモリと予測）を鍛える。',
    variations: ['布・手・ドアの陰など隠し方を変える', '子に隠す役をやらせる'],
    safety: null, related: ['/domains/executive-function/'], updated: '2026-07-06',
  },
  {
    slug: 'dialogic-reading', title: '対話的読み聞かせ', type: 'activity',
    summary: '読み上げるだけでなく問いかけ、子の答えを広げる。語彙と読解の前駆スキルに効くと根拠の強い方法。',
    domains: ['literacy', 'language', 'executive-function'],
    ageRange: { minMonths: 12, maxMonths: 36 }, minutes: 10, effort: 'low', materials: ['絵本'],
    goals: ['勉強に効く'], evidence: 'A',
    father_edge: '父の読みは母と違う声・間・脱線を生む。多様な読み手は言語の幅を広げる。',
    steps: [
      '絵を指して問う（「これ何かな？」「犬は何してる？」）',
      '子の答えを認め、少し足して返す（「そう、犬が走ってるね、速いね」）',
      '子の生活と結びつける（「昨日見た犬みたいだね」）',
      '同じ本を繰り返し読む（反復が語彙定着に効く）',
    ],
    why: '受動的な読み上げより、問い→応答→拡張の往復が表出語彙・物語理解を伸ばす（PEER/CROSHテクニック）。読み聞かせは後の読字力の前駆スキルを育てる。',
    variations: ['月齢が低いうちは指さしと擬音中心で', '結末を子に予想させる'],
    safety: null, related: ['/domains/literacy/', '/domains/language/'], updated: '2026-07-06',
  },
  {
    slug: 'container-play', title: '入れる・出す遊び', type: 'activity',
    summary: '容器に物を出し入れするだけで、微細運動・因果・空間・数量の芽を同時に育てる万能遊び。',
    domains: ['fine-motor', 'math-spatial', 'play'],
    ageRange: { minMonths: 9, maxMonths: 24 }, minutes: 10, effort: 'low',
    materials: ['空き容器', '安全な大きさのブロックやボール'],
    goals: ['勉強に効く'], evidence: 'C',
    father_edge: '工具箱・カラビナ・大きめのボルトなど父の道具箱は格好の素材（誤飲サイズに注意）。',
    steps: ['容器と、握れるサイズの物を用意', '子が自由に出し入れするのを見守る', '「入った」「ぜんぶ出た」「もういっこ」と言葉を添える', '数える・大小を比べるを自然に混ぜる'],
    why: '手指の巧緻性、入れる/出すの因果と空間関係、量の変化（多い少ない・全部空）の直感を育てる。数量認知の非常に初期の土台。',
    variations: ['大小の容器で入れ子（サイズ比較）', '色ごとに分ける（分類）'],
    safety: '誤飲を防ぐため、トイレットペーパーの芯を通る大きさの物は使わない。',
    related: ['/domains/math-spatial/', '/domains/fine-motor/'], updated: '2026-07-06',
  },
  {
    slug: 'rough-and-tumble', title: 'ラフ＆タンブル遊び', type: 'activity',
    summary: '取っ組み合い・転がし合いなど活発な身体遊び。情動調整とリスク学習に効く、父親の代表的な関わり。',
    domains: ['gross-motor', 'social-emotional', 'executive-function'],
    ageRange: { minMonths: 12, maxMonths: 36 }, minutes: 10, effort: 'medium', materials: ['マット・布団などの安全な床'],
    goals: ['スポーツに効く', '情緒'], evidence: 'B',
    father_edge: 'これはまさに父親の得意領域。父との活発な遊びは情動コントロールと関連する。',
    steps: [
      '柔らかい床で、ゆっくり組み合う・転がす・持ち上げる',
      '子の"もっと/やめて"の合図を常に読み、合わせる',
      '興奮が高まったら、クールダウンで締める（落ち着く練習）',
      'ルール（叩かない等）を遊びの中で伝える',
    ],
    why: '興奮を上げて下げる往復が情動調整（自己制御）を鍛える。適度なスリルはリスク評価と身体制御を学ぶ機会になる。',
    variations: ['「よーいドン」で止まる遊びを混ぜEFを刺激', '高い高い（首すわり後・落下注意）'],
    safety: '揺さぶり厳禁。子の"やめて"で必ず止める。頭部の落下に細心の注意。',
    related: ['/domains/gross-motor/', '/fathers-edge/'], updated: '2026-07-06',
  },
  {
    slug: 'naming-walk', title: 'お散歩・名づけ探検', type: 'activity',
    summary: '外を歩きながら見えるものを名づけ、指さしに応じる。語彙・共同注意・好奇心を屋外で育てる。',
    domains: ['language', 'sensory', 'play'],
    ageRange: { minMonths: 6, maxMonths: 36 }, minutes: 15, effort: 'low', materials: [],
    goals: ['勉強に効く'], evidence: 'B',
    father_edge: '父は"寄り道・脱線"を許しやすい。予定より子の興味を優先した探検が好奇心を伸ばす。',
    steps: ['ゆっくり歩き、子が見たものに合わせて名づける', '指さしに「そうだね、◯◯だね」と応じる', '触れる・匂う・聞くを促す（多感覚）', '急がず、子のペースで立ち止まる'],
    why: '共同注意に沿った名づけは語彙獲得の王道。屋外の多感覚刺激は注意と探索意欲を高める。自然接触は情動にも良い。',
    variations: ['色・数・音を探すテーマ散歩', '雨上がりに水たまり・虫を観察'],
    safety: '交通・落下・誤飲に注意。口に入れる時期は拾い食いに気をつける。',
    related: ['/domains/language/', '/domains/play/'], updated: '2026-07-06',
  },
  {
    slug: 'singing-daily', title: '毎日のうた・手遊び', type: 'activity',
    summary: '生活の節目に歌を添える。リズム・音韻・記憶・情動を一度に育て、言語と音楽の土台になる。',
    domains: ['music', 'language', 'executive-function'],
    ageRange: { minMonths: 0, maxMonths: 36 }, minutes: 5, effort: 'low', materials: [],
    goals: ['勉強に効く', '情緒'], evidence: 'B',
    father_edge: '音痴でも問題なし。子は"上手さ"でなく"あなたの声"に反応する。低い声は新鮮な刺激。',
    steps: ['入浴・着替え・寝る前など決まった場面に同じ歌を', '手遊び（むすんでひらいて等）で動作をつける', '子が知る歌はわざと止めて続きを待つ（予測と発声を促す）'],
    why: '歌の韻律は音韻意識（後の読字の土台）を育て、動作系列の記憶がワーキングメモリを刺激。情動の共有が愛着も深める。',
    variations: ['名前や生活を歌詞に入れて即興', 'ゆっくりの歌で寝る前のクールダウン'],
    safety: null, related: ['/domains/music/'], updated: '2026-07-06',
  },
  {
    slug: 'floor-freedom', title: '自由に動ける床の時間', type: 'activity',
    summary: 'ベビーチェアや歩行器に頼らず、安全な床で自由に動かす。運動発達の最良の環境は"自由"。',
    domains: ['gross-motor', 'play'], ageRange: { minMonths: 3, maxMonths: 18 },
    minutes: 20, effort: 'low', materials: ['安全に囲われた床スペース'],
    goals: ['スポーツに効く'], evidence: 'B',
    father_edge: '父は"見守って手を出さない"のが得意なことが多い。転びかけを先回りしすぎない。',
    steps: ['危険物を除いた床スペースを作る', '子を寝かせ/座らせ、自由に動くのを見守る', '少し先に玩具を置き、自発的な移動を誘う', '手を出しすぎず、挑戦と小さな失敗を許す'],
    why: '自発的な運動の反復が、寝返り〜はいはい〜歩行の発達を支える。歩行器はむしろ発達を遅らせうるとの指摘があり推奨されない。',
    variations: ['クッションの山で登る・降りる', '大きめのボールを転がして追わせる'],
    safety: '角・コード・小物・階段に注意。歩行器の使用は避ける（転倒・発達面の懸念）。',
    related: ['/domains/gross-motor/', '/roadmap/6-9/'], updated: '2026-07-06',
  },
  {
    slug: 'emotion-labeling', title: '気持ちの実況（感情のことば化）', type: 'activity',
    summary: '子の感情に名前をつけて返す。情動理解・共感・自己制御の土台をつくる。',
    domains: ['social-emotional', 'language', 'executive-function'],
    ageRange: { minMonths: 6, maxMonths: 36 }, minutes: 3, effort: 'low', materials: [],
    goals: ['情緒', '勉強に効く'], evidence: 'B',
    father_edge: '父が感情を言葉にする姿は「強さ＝我慢」ではなく「感情を扱える」モデルになる。',
    steps: ['子が感情を示したら名づける（「悔しかったね」「うれしいね」）', '受け止めてから対処（「悔しいね。もう一回やってみる？」）', '父自身の感情も時々言葉にして見せる'],
    why: '感情をラベリングされる経験は情動の理解と調整（前頭前皮質による扁桃体の制御）を育てる。感情語彙は後の社会性・EFに効く。',
    variations: ['絵本の登場人物の気持ちを一緒に考える'],
    safety: null, related: ['/domains/social-emotional/', '/domains/executive-function/'], updated: '2026-07-06',
  },
];
